-- created by Oraschemadoc Wed Aug 30 22:57:17 2017
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE UNIQUE INDEX "SPACEUSER"."RHN_ISSM_ONLY_ONE_DEFAULT" ON "SPACEUSER"."RHNISSMASTER" (CASE  WHEN "IS_CURRENT_MASTER"='Y' THEN "IS_CURRENT_MASTER" END ) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
/
