-- created by Oraschemadoc Wed Mar  4 07:58:10 2020
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE UNIQUE INDEX "SPACEUSER"."SYS_C009292" ON "SPACEUSER"."QRTZ_TRIGGER_LISTENERS" ("TRIGGER_NAME", "TRIGGER_GROUP", "TRIGGER_LISTENER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
/
