-- created by Oraschemadoc Wed Jan  9 15:07:17 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE UNIQUE INDEX "SPACEUSER"."RHN_SACTIONVM_SANEC_UQ" ON "SPACEUSER"."RHNSERVERACTIONVERIFYMISSING" ("SERVER_ID", "ACTION_ID", "PACKAGE_NAME_ID", "PACKAGE_EVR_ID", "PACKAGE_ARCH_ID", "PACKAGE_CAPABILITY_ID")
  ;
