-- created by Oraschemadoc Wed Aug 30 22:56:29 2017
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."QRTZ_JOB_LISTENERS" 
   (	"JOB_NAME" VARCHAR2(200) NOT NULL ENABLE, 
	"JOB_GROUP" VARCHAR2(200) NOT NULL ENABLE, 
	"JOB_LISTENER" VARCHAR2(200) NOT NULL ENABLE, 
	 PRIMARY KEY ("JOB_NAME", "JOB_GROUP", "JOB_LISTENER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 FOREIGN KEY ("JOB_NAME", "JOB_GROUP")
	  REFERENCES "SPACEUSER"."QRTZ_JOB_DETAILS" ("JOB_NAME", "JOB_GROUP") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
/
