-- created by Oraschemadoc Wed Apr 11 12:21:54 2018
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIONPACKAGEDELTA" 
   (	"ACTION_ID" NUMBER NOT NULL ENABLE, 
	"PACKAGE_DELTA_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ACT_PD_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "SPACEUSER"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ACT_PD_PDID_FK" FOREIGN KEY ("PACKAGE_DELTA_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEDELTA" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE ROW MOVEMENT 
/
