-- created by Oraschemadoc Wed Apr 11 12:21:56 2018
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNARCHTYPEACTIONS" 
   (	"ARCH_TYPE_ID" NUMBER NOT NULL ENABLE, 
	"ACTION_STYLE" VARCHAR2(64) NOT NULL ENABLE, 
	"ACTION_TYPE_ID" NUMBER NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE, 
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ARCHTYPEACTS_ATID_FK" FOREIGN KEY ("ARCH_TYPE_ID")
	  REFERENCES "SPACEUSER"."RHNARCHTYPE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_ARCHTYPEACTS_ACTID_FK" FOREIGN KEY ("ACTION_TYPE_ID")
	  REFERENCES "SPACEUSER"."RHNACTIONTYPE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE ROW MOVEMENT 
/
