-- created by Oraschemadoc Wed Mar  4 07:57:23 2020
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIONCHAINENTRY" 
   (	"ACTIONCHAIN_ID" NUMBER NOT NULL ENABLE, 
	"ACTION_ID" NUMBER, 
	"SERVER_ID" NUMBER NOT NULL ENABLE, 
	"SORT_ORDER" NUMBER NOT NULL ENABLE, 
	"CREATED" DATE DEFAULT (SYSDATE) NOT NULL ENABLE, 
	"MODIFIED" DATE DEFAULT (SYSDATE) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ACTCHAINENT_ACID_FK" FOREIGN KEY ("ACTIONCHAIN_ID")
	  REFERENCES "SPACEUSER"."RHNACTIONCHAIN" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ACTCHAINENT_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "SPACEUSER"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ACTCHAINENT_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE ROW MOVEMENT 
/
