-- created by Oraschemadoc Wed Apr 11 12:21:52 2018
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTION" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"ORG_ID" NUMBER NOT NULL ENABLE, 
	"ACTION_TYPE" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(128), 
	"SCHEDULER" NUMBER, 
	"EARLIEST_ACTION" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"VERSION" NUMBER DEFAULT (0) NOT NULL ENABLE, 
	"ARCHIVED" NUMBER DEFAULT (0) NOT NULL ENABLE, 
	"PREREQUISITE" NUMBER, 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE, 
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ACTION_ARCHIVED_CK" CHECK (archived in (0, 1)) ENABLE, 
	 CONSTRAINT "RHN_ACTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "RHN_ACTION_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ACTION_AT_FK" FOREIGN KEY ("ACTION_TYPE")
	  REFERENCES "SPACEUSER"."RHNACTIONTYPE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_ACTION_SCHEDULER_FK" FOREIGN KEY ("SCHEDULER")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_ACTION_PREREQ_FK" FOREIGN KEY ("PREREQUISITE")
	  REFERENCES "SPACEUSER"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE ROW MOVEMENT 
/
