-- created by Oraschemadoc Wed Mar  4 07:57:29 2020
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCRYPTOKEYKICKSTART" 
   (	"CRYPTO_KEY_ID" NUMBER NOT NULL ENABLE, 
	"KSDATA_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RHN_CKEY_KS_CKID_FK" FOREIGN KEY ("CRYPTO_KEY_ID")
	  REFERENCES "SPACEUSER"."RHNCRYPTOKEY" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_CKEY_KS_KSD_FK" FOREIGN KEY ("KSDATA_ID")
	  REFERENCES "SPACEUSER"."RHNKSDATA" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE ROW MOVEMENT 
/
