-- created by Oraschemadoc Wed Apr 11 12:22:03 2018
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNFILELOCATION" 
   (	"FILE_ID" NUMBER NOT NULL ENABLE, 
	"LOCATION" VARCHAR2(128) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_FILELOC_FID_FK" FOREIGN KEY ("FILE_ID")
	  REFERENCES "SPACEUSER"."RHNFILE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE ROW MOVEMENT 
/
