-- created by Oraschemadoc Wed Apr 11 12:22:04 2018
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNISSMASTERORGS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"MASTER_ID" NUMBER NOT NULL ENABLE, 
	"MASTER_ORG_ID" NUMBER NOT NULL ENABLE, 
	"MASTER_ORG_NAME" VARCHAR2(512) NOT NULL ENABLE, 
	"LOCAL_ORG_ID" NUMBER, 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_ISSMASTERORGS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "RHN_ISSMASTERORGS_CID_FK" FOREIGN KEY ("MASTER_ID")
	  REFERENCES "SPACEUSER"."RHNISSMASTER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_ISSMASTERORGS_LID_FK" FOREIGN KEY ("LOCAL_ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
/
