-- created by Oraschemadoc Wed Aug 30 22:56:43 2017
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNKICKSTARTDEFAULTS" 
   (	"KICKSTART_ID" NUMBER NOT NULL ENABLE, 
	"KSTREE_ID" NUMBER NOT NULL ENABLE, 
	"SERVER_PROFILE_ID" NUMBER, 
	"CFG_MANAGEMENT_FLAG" CHAR(1) DEFAULT ('Y') NOT NULL ENABLE, 
	"REMOTE_COMMAND_FLAG" CHAR(1) DEFAULT ('N') NOT NULL ENABLE, 
	"VIRTUALIZATION_TYPE" NUMBER NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE, 
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_KSD_CMF_CK" CHECK (cfg_management_flag in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_KSD_RMF_CK" CHECK (remote_command_flag in ('Y','N')) ENABLE, 
	 CONSTRAINT "RHN_KSD_KSID_UQ" UNIQUE ("KICKSTART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "RHN_KSD_KSID_FK" FOREIGN KEY ("KICKSTART_ID")
	  REFERENCES "SPACEUSER"."RHNKSDATA" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_KSD_KSTID_FK" FOREIGN KEY ("KSTREE_ID")
	  REFERENCES "SPACEUSER"."RHNKICKSTARTABLETREE" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_KSD_SPID_FK" FOREIGN KEY ("SERVER_PROFILE_ID")
	  REFERENCES "SPACEUSER"."RHNSERVERPROFILE" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_KSD_KVT_FK" FOREIGN KEY ("VIRTUALIZATION_TYPE")
	  REFERENCES "SPACEUSER"."RHNKICKSTARTVIRTUALIZATIONTYPE" ("ID") ON DELETE SET NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE ROW MOVEMENT 
/
