-- created by Oraschemadoc Wed Mar  4 07:57:35 2020
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNPACKAGEDELTAELEMENT" 
   (	"PACKAGE_DELTA_ID" NUMBER NOT NULL ENABLE, 
	"TRANSACTION_PACKAGE_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RHN_PDELEMENT_PDID_FK" FOREIGN KEY ("PACKAGE_DELTA_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEDELTA" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_PDELEMENT_TPID_FK" FOREIGN KEY ("TRANSACTION_PACKAGE_ID")
	  REFERENCES "SPACEUSER"."RHNTRANSACTIONPACKAGE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE ROW MOVEMENT 
/
