-- created by Oraschemadoc Wed Mar  4 07:57:44 2020
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSYSTEMMIGRATIONS" 
   (	"ORG_ID_TO" NUMBER, 
	"ORG_ID_FROM" NUMBER, 
	"SERVER_ID" NUMBER NOT NULL ENABLE, 
	"MIGRATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SYS_MIG_OIDTO_FK" FOREIGN KEY ("ORG_ID_TO")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_SYS_MIG_OIDFRM_FK" FOREIGN KEY ("ORG_ID_FROM")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE SET NULL ENABLE, 
	 CONSTRAINT "RHN_SYS_MIG_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE ROW MOVEMENT 
/
