-- created by Oraschemadoc Wed Mar  4 07:57:43 2020
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVER_LOG" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"LOG_ID" NUMBER NOT NULL ENABLE, 
	"ACTION" CHAR(1) NOT NULL ENABLE, 
	"ORG_ID" NUMBER NOT NULL ENABLE, 
	"DIGITAL_SERVER_ID" VARCHAR2(64) NOT NULL ENABLE, 
	"SERVER_ARCH_ID" NUMBER NOT NULL ENABLE, 
	"OS" VARCHAR2(64) NOT NULL ENABLE, 
	"RELEASE" VARCHAR2(64) NOT NULL ENABLE, 
	"NAME" VARCHAR2(128), 
	"DESCRIPTION" VARCHAR2(256), 
	"INFO" VARCHAR2(128), 
	"SECRET" VARCHAR2(64) NOT NULL ENABLE, 
	"CREATOR_ID" NUMBER, 
	"AUTO_UPDATE" CHAR(1) NOT NULL ENABLE, 
	"RUNNING_KERNEL" VARCHAR2(64), 
	"LAST_BOOT" NUMBER NOT NULL ENABLE, 
	"PROVISION_STATE_ID" NUMBER, 
	"CHANNELS_CHANGED" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"COBBLER_ID" VARCHAR2(64), 
	 FOREIGN KEY ("LOG_ID")
	  REFERENCES "SPACEUSER"."LOG" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
/
