-- created by Oraschemadoc Wed Mar  4 07:57:40 2020
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVERCRASHFILE" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"CRASH_ID" NUMBER NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(512) NOT NULL ENABLE, 
	"PATH" VARCHAR2(1024) NOT NULL ENABLE, 
	"FILESIZE" NUMBER NOT NULL ENABLE, 
	"IS_UPLOADED" CHAR(1) DEFAULT ('N') NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE, 
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_SERVER_CRASH_FILE_UPL_CK" CHECK (is_uploaded in ('Y', 'N')) ENABLE, 
	 CONSTRAINT "RHN_SERVER_CRASH_FILE_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "RHN_SERVER_CRASH_FILE_CIS_FK" FOREIGN KEY ("CRASH_ID")
	  REFERENCES "SPACEUSER"."RHNSERVERCRASH" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE ROW MOVEMENT 
/
