-- created by Oraschemadoc Wed Aug 30 22:56:53 2017
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVERGROUP_LOG" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"LOG_ID" NUMBER NOT NULL ENABLE, 
	"ACTION" CHAR(1) NOT NULL ENABLE, 
	"NAME" VARCHAR2(64) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(1024) NOT NULL ENABLE, 
	"CURRENT_MEMBERS" NUMBER NOT NULL ENABLE, 
	"GROUP_TYPE" NUMBER, 
	"ORG_ID" NUMBER NOT NULL ENABLE, 
	 FOREIGN KEY ("LOG_ID")
	  REFERENCES "SPACEUSER"."LOG" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
/
