-- created by Oraschemadoc Wed Apr 11 12:22:17 2018
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSSMOPERATIONSERVER" 
   (	"OPERATION_ID" NUMBER, 
	"SERVER_ID" NUMBER, 
	"NOTE" VARCHAR2(256) DEFAULT NULL, 
	 CONSTRAINT "RHN_SSMOPS_SSMOP_FK" FOREIGN KEY ("OPERATION_ID")
	  REFERENCES "SPACEUSER"."RHNSSMOPERATION" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_SSMOPS_SER_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
/
