-- created by Oraschemadoc Wed Mar  4 07:57:44 2020
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNTASKORUN" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TEMPLATE_ID" NUMBER NOT NULL ENABLE, 
	"SCHEDULE_ID" NUMBER NOT NULL ENABLE, 
	"ORG_ID" NUMBER, 
	"START_TIME" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"END_TIME" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"STD_OUTPUT_PATH" VARCHAR2(100), 
	"STD_ERROR_PATH" VARCHAR2(100), 
	"STATUS" VARCHAR2(12), 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE, 
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_TASKO_RUN_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "RHN_TASKO_RUN_TEMPLATE_FK" FOREIGN KEY ("TEMPLATE_ID")
	  REFERENCES "SPACEUSER"."RHNTASKOTEMPLATE" ("ID") ENABLE, 
	 CONSTRAINT "RHN_TASKO_RUN_SCHEDULE_FK" FOREIGN KEY ("SCHEDULE_ID")
	  REFERENCES "SPACEUSER"."RHNTASKOSCHEDULE" ("ID") ON DELETE CASCADE ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
/
