-- created by Oraschemadoc Wed Aug 30 22:56:58 2017
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNUSERGROUPMEMBERS" 
   (	"USER_ID" NUMBER NOT NULL ENABLE, 
	"USER_GROUP_ID" NUMBER NOT NULL ENABLE, 
	"TEMPORARY" CHAR(1) DEFAULT ('N') NOT NULL ENABLE, 
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE, 
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE, 
	 CONSTRAINT "RHN_UGMEMBERS_T_CK" CHECK (temporary in ('Y', 'N')) ENABLE, 
	 CONSTRAINT "RHN_UGMEMBERS_UID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_UGMEMBERS_UGID_FK" FOREIGN KEY ("USER_GROUP_ID")
	  REFERENCES "SPACEUSER"."RHNUSERGROUP" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE ROW MOVEMENT 
/
