-- created by Oraschemadoc Wed Aug 30 22:57:03 2017
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNXCCDFRULERESULT" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"TESTRESULT_ID" NUMBER NOT NULL ENABLE, 
	"RESULT_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RHN_XCCDF_RRESULT_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "RHN_XCCDF_RRESULT_TRESULT_FK" FOREIGN KEY ("TESTRESULT_ID")
	  REFERENCES "SPACEUSER"."RHNXCCDFTESTRESULT" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_XCCDF_RRESULT_RESULT_FK" FOREIGN KEY ("RESULT_ID")
	  REFERENCES "SPACEUSER"."RHNXCCDFRULERESULTTYPE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE ROW MOVEMENT 
/
