-- created by Oraschemadoc Wed Mar  4 07:57:48 2020
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNXCCDFTESTRESULT" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"SERVER_ID" NUMBER NOT NULL ENABLE, 
	"ACTION_SCAP_ID" NUMBER NOT NULL ENABLE, 
	"BENCHMARK_ID" NUMBER NOT NULL ENABLE, 
	"PROFILE_ID" NUMBER NOT NULL ENABLE, 
	"IDENTIFIER" VARCHAR2(120) NOT NULL ENABLE, 
	"START_TIME" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"END_TIME" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"ERRORS" BLOB, 
	 CONSTRAINT "RHN_XCCDF_TRESULT_ID_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "RHN_XCCDF_TRESULT_SRVR_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_XCCDF_TRESULT_ACT_FK" FOREIGN KEY ("ACTION_SCAP_ID")
	  REFERENCES "SPACEUSER"."RHNACTIONSCAP" ("ID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "RHN_XCCDF_TRESULT_BENCH_FK" FOREIGN KEY ("BENCHMARK_ID")
	  REFERENCES "SPACEUSER"."RHNXCCDFBENCHMARK" ("ID") ENABLE, 
	 CONSTRAINT "RHN_XCCDF_TRESULT_PROFILE_FK" FOREIGN KEY ("PROFILE_ID")
	  REFERENCES "SPACEUSER"."RHNXCCDFPROFILE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("ERRORS") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT))  ENABLE ROW MOVEMENT 
/
