-- created by Oraschemadoc Wed Jan  9 15:06:51 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."LOG"
   (	"ID" NUMBER NOT NULL ENABLE,
	"STAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"USER_ID" NUMBER
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."LOG" ADD CONSTRAINT "LOG_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."LOG" ADD CONSTRAINT "LOG_USER_ID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "SPACEUSER"."WEB_CONTACT_ALL" ("ID") ENABLE;
