-- created by Oraschemadoc Wed Jan  9 15:06:51 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."PXTSESSIONS"
   (	"ID" NUMBER,
	"WEB_USER_ID" NUMBER,
	"EXPIRES" NUMBER DEFAULT (0) NOT NULL ENABLE,
	"VALUE" VARCHAR2(4000) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."PXTSESSIONS" ADD CONSTRAINT "PXT_SESSIONS_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."PXTSESSIONS" ADD CONSTRAINT "PXTSESSIONS_USER" FOREIGN KEY ("WEB_USER_ID")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE;
