-- created by Oraschemadoc Wed Jan  9 15:06:52 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."QRTZ_JOB_DETAILS"
   (	"JOB_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"JOB_GROUP" VARCHAR2(200) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(250),
	"JOB_CLASS_NAME" VARCHAR2(250) NOT NULL ENABLE,
	"IS_DURABLE" VARCHAR2(1) NOT NULL ENABLE,
	"IS_VOLATILE" VARCHAR2(1) NOT NULL ENABLE,
	"IS_STATEFUL" VARCHAR2(1) NOT NULL ENABLE,
	"REQUESTS_RECOVERY" VARCHAR2(1) NOT NULL ENABLE,
	"JOB_DATA" BLOB
   ) ;
  ALTER TABLE "SPACEUSER"."QRTZ_JOB_DETAILS" ADD PRIMARY KEY ("JOB_NAME", "JOB_GROUP") ENABLE;
