-- created by Oraschemadoc Wed Jan  9 15:06:52 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."QRTZ_SIMPLE_TRIGGERS"
   (	"TRIGGER_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"TRIGGER_GROUP" VARCHAR2(200) NOT NULL ENABLE,
	"REPEAT_COUNT" NUMBER(7,0) NOT NULL ENABLE,
	"REPEAT_INTERVAL" NUMBER(12,0) NOT NULL ENABLE,
	"TIMES_TRIGGERED" NUMBER(10,0) NOT NULL ENABLE
   ) ;
  ALTER TABLE "SPACEUSER"."QRTZ_SIMPLE_TRIGGERS" ADD PRIMARY KEY ("TRIGGER_NAME", "TRIGGER_GROUP") ENABLE;
  ALTER TABLE "SPACEUSER"."QRTZ_SIMPLE_TRIGGERS" ADD FOREIGN KEY ("TRIGGER_NAME", "TRIGGER_GROUP")
	  REFERENCES "SPACEUSER"."QRTZ_TRIGGERS" ("TRIGGER_NAME", "TRIGGER_GROUP") ENABLE;
