-- created by Oraschemadoc Wed Jan  9 15:06:52 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."QRTZ_JOB_LISTENERS"
   (	"JOB_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"JOB_GROUP" VARCHAR2(200) NOT NULL ENABLE,
	"JOB_LISTENER" VARCHAR2(200) NOT NULL ENABLE
   ) ;
  ALTER TABLE "SPACEUSER"."QRTZ_JOB_LISTENERS" ADD PRIMARY KEY ("JOB_NAME", "JOB_GROUP", "JOB_LISTENER") ENABLE;
  ALTER TABLE "SPACEUSER"."QRTZ_JOB_LISTENERS" ADD FOREIGN KEY ("JOB_NAME", "JOB_GROUP")
	  REFERENCES "SPACEUSER"."QRTZ_JOB_DETAILS" ("JOB_NAME", "JOB_GROUP") ENABLE;
