-- created by Oraschemadoc Wed Jan  9 15:06:52 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."QRTZ_SCHEDULER_STATE"
   (	"INSTANCE_NAME" VARCHAR2(200) NOT NULL ENABLE,
	"LAST_CHECKIN_TIME" NUMBER(13,0) NOT NULL ENABLE,
	"CHECKIN_INTERVAL" NUMBER(13,0) NOT NULL ENABLE
   ) ;
  ALTER TABLE "SPACEUSER"."QRTZ_SCHEDULER_STATE" ADD PRIMARY KEY ("INSTANCE_NAME") ENABLE;
