-- created by Oraschemadoc Wed Jan  9 15:06:54 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIONVIRTSCHEDULEPOLLER"
   (	"ACTION_ID" NUMBER NOT NULL ENABLE,
	"MINUTE" NUMBER,
	"HOUR" NUMBER,
	"DOM" NUMBER,
	"MONTH" NUMBER,
	"DOW" NUMBER,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNACTIONVIRTSCHEDULEPOLLER" ADD CONSTRAINT "RHN_AVSP_AID_PK" PRIMARY KEY ("ACTION_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONVIRTSCHEDULEPOLLER" ADD CONSTRAINT "RHN_AVSP_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "SPACEUSER"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE;
