-- created by Oraschemadoc Wed Jan  9 15:06:54 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIVATIONKEY"
   (	"TOKEN" VARCHAR2(48) NOT NULL ENABLE,
	"REG_TOKEN_ID" NUMBER NOT NULL ENABLE,
	"KS_SESSION_ID" NUMBER,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNACTIVATIONKEY" ADD CONSTRAINT "RHN_ACT_KEY_TOKEN_UQ" UNIQUE ("TOKEN") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIVATIONKEY" ADD CONSTRAINT "RHN_ACT_KEY_REG_TID_FK" FOREIGN KEY ("REG_TOKEN_ID")
	  REFERENCES "SPACEUSER"."RHNREGTOKEN" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIVATIONKEY" ADD CONSTRAINT "RHN_ACT_KEY_KS_SID_FK" FOREIGN KEY ("KS_SESSION_ID")
	  REFERENCES "SPACEUSER"."RHNKICKSTARTSESSION" ("ID") ON DELETE CASCADE ENABLE;
