-- created by Oraschemadoc Wed Jan  9 15:06:53 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIONIMAGEDEPLOY"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ACTION_ID" NUMBER NOT NULL ENABLE,
	"VCPUS" NUMBER NOT NULL ENABLE,
	"MEM_KB" NUMBER NOT NULL ENABLE,
	"BRIDGE_DEVICE" VARCHAR2(32),
	"DOWNLOAD_URL" VARCHAR2(256) NOT NULL ENABLE,
	"PROXY_SERVER" VARCHAR2(64),
	"PROXY_USER" VARCHAR2(32),
	"PROXY_PASS" VARCHAR2(64)
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNACTIONIMAGEDEPLOY" ADD CONSTRAINT "RHN_AID_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONIMAGEDEPLOY" ADD CONSTRAINT "RHN_ACT_IDP_ACT_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "SPACEUSER"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE;
