-- created by Oraschemadoc Wed Jan  9 15:06:52 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIONCONFIGCHANNEL"
   (	"ACTION_ID" NUMBER NOT NULL ENABLE,
	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"CONFIG_CHANNEL_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNACTIONCONFIGCHANNEL" ADD CONSTRAINT "RHN_ACTIONCC_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "SPACEUSER"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONCONFIGCHANNEL" ADD CONSTRAINT "RHN_ACTIONCC_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONCONFIGCHANNEL" ADD CONSTRAINT "RHN_ACTIONCC_CCID_FK" FOREIGN KEY ("CONFIG_CHANNEL_ID")
	  REFERENCES "SPACEUSER"."RHNCONFIGCHANNEL" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONCONFIGCHANNEL" ADD CONSTRAINT "RHN_ACTIONCC_SID_AID_FK" FOREIGN KEY ("SERVER_ID", "ACTION_ID")
	  REFERENCES "SPACEUSER"."RHNSERVERACTION" ("SERVER_ID", "ACTION_ID") ON DELETE CASCADE ENABLE;
