-- created by Oraschemadoc Wed Jan  9 15:06:52 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIONCHAINENTRY"
   (	"ACTIONCHAIN_ID" NUMBER NOT NULL ENABLE,
	"ACTION_ID" NUMBER,
	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"SORT_ORDER" NUMBER NOT NULL ENABLE,
	"CREATED" DATE DEFAULT (SYSDATE) NOT NULL ENABLE,
	"MODIFIED" DATE DEFAULT (SYSDATE) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNACTIONCHAINENTRY" ADD CONSTRAINT "RHN_ACTCHAINENT_ACID_FK" FOREIGN KEY ("ACTIONCHAIN_ID")
	  REFERENCES "SPACEUSER"."RHNACTIONCHAIN" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONCHAINENTRY" ADD CONSTRAINT "RHN_ACTCHAINENT_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "SPACEUSER"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONCHAINENTRY" ADD CONSTRAINT "RHN_ACTCHAINENT_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ON DELETE CASCADE ENABLE;
