-- created by Oraschemadoc Wed Jan  9 15:06:53 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIONKICKSTARTGUEST"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ACTION_ID" NUMBER NOT NULL ENABLE,
	"APPEND_STRING" VARCHAR2(1024),
	"KS_SESSION_ID" NUMBER,
	"GUEST_NAME" VARCHAR2(256),
	"MEM_KB" NUMBER,
	"VCPUS" NUMBER,
	"DISK_GB" NUMBER,
	"COBBLER_SYSTEM_NAME" VARCHAR2(256),
	"DISK_PATH" VARCHAR2(256),
	"VIRT_BRIDGE" VARCHAR2(256),
	"KICKSTART_HOST" VARCHAR2(256),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MAC_ADDRESS" VARCHAR2(17)
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNACTIONKICKSTARTGUEST" ADD CONSTRAINT "RHN_ACTIONKS_XENGUEST_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONKICKSTARTGUEST" ADD CONSTRAINT "RHN_ACTIONKS_XENGUEST_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "SPACEUSER"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONKICKSTARTGUEST" ADD CONSTRAINT "RHN_ACTIONKS_XENGUEST_KSID_FK" FOREIGN KEY ("KS_SESSION_ID")
	  REFERENCES "SPACEUSER"."RHNKICKSTARTSESSION" ("ID") ON DELETE CASCADE ENABLE;
