-- created by Oraschemadoc Wed Jan  9 15:06:53 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIONPACKAGEREMOVALFAILURE"
   (	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"ACTION_ID" NUMBER NOT NULL ENABLE,
	"NAME_ID" NUMBER NOT NULL ENABLE,
	"EVR_ID" NUMBER NOT NULL ENABLE,
	"CAPABILITY_ID" NUMBER NOT NULL ENABLE,
	"FLAGS" NUMBER NOT NULL ENABLE,
	"SUGGESTED" NUMBER,
	"SENSE" NUMBER NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNACTIONPACKAGEREMOVALFAILURE" ADD CONSTRAINT "RHN_APR_FAILURE_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONPACKAGEREMOVALFAILURE" ADD CONSTRAINT "RHN_APR_FAILURE_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "SPACEUSER"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONPACKAGEREMOVALFAILURE" ADD CONSTRAINT "RHN_APR_FAILURE_NID_FK" FOREIGN KEY ("NAME_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGENAME" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONPACKAGEREMOVALFAILURE" ADD CONSTRAINT "RHN_APR_FAILURE_EID_FK" FOREIGN KEY ("EVR_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEEVR" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONPACKAGEREMOVALFAILURE" ADD CONSTRAINT "RHN_APR_FAILURE_CAPID_FK" FOREIGN KEY ("CAPABILITY_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGECAPABILITY" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONPACKAGEREMOVALFAILURE" ADD CONSTRAINT "RHN_APR_FAILURE_SUGGESTED_FK" FOREIGN KEY ("SUGGESTED")
	  REFERENCES "SPACEUSER"."RHNPACKAGENAME" ("ID") ENABLE;
