-- created by Oraschemadoc Wed Jan  9 15:06:53 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIONCONFIGDATEFILE"
   (	"ACTION_ID" NUMBER NOT NULL ENABLE,
	"FILE_NAME" VARCHAR2(512) NOT NULL ENABLE,
	"FILE_TYPE" CHAR(1) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNACTIONCONFIGDATEFILE" ADD CONSTRAINT "RHN_ACTIONCD_FILE_FT_CK" CHECK (file_type in ('W','B')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONCONFIGDATEFILE" ADD CONSTRAINT "RHN_ACTIONCD_FILE_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "SPACEUSER"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE;
