-- created by Oraschemadoc Wed Jan  9 15:06:54 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNARCHTYPEACTIONS"
   (	"ARCH_TYPE_ID" NUMBER NOT NULL ENABLE,
	"ACTION_STYLE" VARCHAR2(64) NOT NULL ENABLE,
	"ACTION_TYPE_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNARCHTYPEACTIONS" ADD CONSTRAINT "RHN_ARCHTYPEACTS_ATID_FK" FOREIGN KEY ("ARCH_TYPE_ID")
	  REFERENCES "SPACEUSER"."RHNARCHTYPE" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNARCHTYPEACTIONS" ADD CONSTRAINT "RHN_ARCHTYPEACTS_ACTID_FK" FOREIGN KEY ("ACTION_TYPE_ID")
	  REFERENCES "SPACEUSER"."RHNACTIONTYPE" ("ID") ENABLE;
