-- created by Oraschemadoc Wed Jan  9 15:06:53 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIONCONFIGFILENAME"
   (	"ACTION_ID" NUMBER NOT NULL ENABLE,
	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"CONFIG_FILE_NAME_ID" NUMBER NOT NULL ENABLE,
	"CONFIG_REVISION_ID" NUMBER,
	"FAILURE_ID" NUMBER,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNACTIONCONFIGFILENAME" ADD CONSTRAINT "RHN_ACTIONCF_NAME_CFNID_FK" FOREIGN KEY ("CONFIG_FILE_NAME_ID")
	  REFERENCES "SPACEUSER"."RHNCONFIGFILENAME" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONCONFIGFILENAME" ADD CONSTRAINT "RHN_ACTIONCF_NAME_CRID_FK" FOREIGN KEY ("CONFIG_REVISION_ID")
	  REFERENCES "SPACEUSER"."RHNCONFIGREVISION" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONCONFIGFILENAME" ADD CONSTRAINT "RHN_ACTIONCF_FAILURE_ID_FK" FOREIGN KEY ("FAILURE_ID")
	  REFERENCES "SPACEUSER"."RHNCONFIGFILEFAILURE" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONCONFIGFILENAME" ADD CONSTRAINT "RHN_ACTIONCF_NAME_AID_SID_FK" FOREIGN KEY ("SERVER_ID", "ACTION_ID")
	  REFERENCES "SPACEUSER"."RHNSERVERACTION" ("SERVER_ID", "ACTION_ID") ON DELETE CASCADE ENABLE;
