-- created by Oraschemadoc Wed Jan  9 15:06:52 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTION"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ORG_ID" NUMBER NOT NULL ENABLE,
	"ACTION_TYPE" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(128),
	"SCHEDULER" NUMBER,
	"EARLIEST_ACTION" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE,
	"VERSION" NUMBER DEFAULT (0) NOT NULL ENABLE,
	"ARCHIVED" NUMBER DEFAULT (0) NOT NULL ENABLE,
	"PREREQUISITE" NUMBER,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNACTION" ADD CONSTRAINT "RHN_ACTION_ARCHIVED_CK" CHECK (archived in (0, 1)) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTION" ADD CONSTRAINT "RHN_ACTION_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTION" ADD CONSTRAINT "RHN_ACTION_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTION" ADD CONSTRAINT "RHN_ACTION_AT_FK" FOREIGN KEY ("ACTION_TYPE")
	  REFERENCES "SPACEUSER"."RHNACTIONTYPE" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTION" ADD CONSTRAINT "RHN_ACTION_SCHEDULER_FK" FOREIGN KEY ("SCHEDULER")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTION" ADD CONSTRAINT "RHN_ACTION_PREREQ_FK" FOREIGN KEY ("PREREQUISITE")
	  REFERENCES "SPACEUSER"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE;
