-- created by Oraschemadoc Wed Jan  9 15:06:52 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIONCHAIN"
   (	"ID" NUMBER NOT NULL ENABLE,
	"LABEL" VARCHAR2(256) NOT NULL ENABLE,
	"USER_ID" NUMBER NOT NULL ENABLE,
	"CREATED" DATE DEFAULT (SYSDATE) NOT NULL ENABLE,
	"MODIFIED" DATE DEFAULT (SYSDATE) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNACTIONCHAIN" ADD CONSTRAINT "RHN_ACTION_CHAIN_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONCHAIN" ADD CONSTRAINT "RHN_ACTIONCHAIN_UID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE;
