-- created by Oraschemadoc Wed Jan  9 15:06:53 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIONDAEMONCONFIG"
   (	"ACTION_ID" NUMBER NOT NULL ENABLE,
	"INTERVAL" NUMBER NOT NULL ENABLE,
	"RESTART" CHAR(1) DEFAULT ('Y') NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNACTIONDAEMONCONFIG" ADD CONSTRAINT "RHN_ACTIONDC_REST_CK" CHECK (restart in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONDAEMONCONFIG" ADD CONSTRAINT "RHN_ACTIONDC_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "SPACEUSER"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE;
