-- created by Oraschemadoc Wed Jan  9 15:06:53 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIONTYPE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"LABEL" VARCHAR2(48) NOT NULL ENABLE,
	"NAME" VARCHAR2(100) NOT NULL ENABLE,
	"TRIGGER_SNAPSHOT" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"UNLOCKED_ONLY" CHAR(1) DEFAULT ('N') NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNACTIONTYPE" ADD CONSTRAINT "RHN_ACTION_TYPE_TRIGSNAP_CK" CHECK (trigger_snapshot in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONTYPE" ADD CONSTRAINT "RHN_ACTION_TYPE_UNLCK_CK" CHECK (unlocked_only in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONTYPE" ADD CONSTRAINT "RHN_ACTION_TYPE_PK" PRIMARY KEY ("ID") ENABLE;
