-- created by Oraschemadoc Wed Jan  9 15:06:53 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIONPACKAGE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ACTION_ID" NUMBER NOT NULL ENABLE,
	"PARAMETER" VARCHAR2(128) DEFAULT ('upgrade') NOT NULL ENABLE,
	"NAME_ID" NUMBER NOT NULL ENABLE,
	"EVR_ID" NUMBER,
	"PACKAGE_ARCH_ID" NUMBER
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNACTIONPACKAGE" ADD CONSTRAINT "RHN_ACT_P_PARAM_CK" CHECK (parameter IN ('upgrade', 'install', 'remove', 'downgrade')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONPACKAGE" ADD CONSTRAINT "RHN_ACT_P_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONPACKAGE" ADD CONSTRAINT "RHN_ACT_P_ACT_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "SPACEUSER"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONPACKAGE" ADD CONSTRAINT "RHN_ACT_P_NAME_FK" FOREIGN KEY ("NAME_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGENAME" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONPACKAGE" ADD CONSTRAINT "RHN_ACT_P_EVR_FK" FOREIGN KEY ("EVR_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEEVR" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONPACKAGE" ADD CONSTRAINT "RHN_ACT_P_PAID_FK" FOREIGN KEY ("PACKAGE_ARCH_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEARCH" ("ID") ENABLE;
