-- created by Oraschemadoc Wed Jan  9 15:06:53 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIONPACKAGEDELTA"
   (	"ACTION_ID" NUMBER NOT NULL ENABLE,
	"PACKAGE_DELTA_ID" NUMBER NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNACTIONPACKAGEDELTA" ADD CONSTRAINT "RHN_ACT_PD_AID_FK" FOREIGN KEY ("ACTION_ID")
	  REFERENCES "SPACEUSER"."RHNACTION" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNACTIONPACKAGEDELTA" ADD CONSTRAINT "RHN_ACT_PD_PDID_FK" FOREIGN KEY ("PACKAGE_DELTA_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEDELTA" ("ID") ON DELETE CASCADE ENABLE;
