-- created by Oraschemadoc Wed Jan  9 15:06:53 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNACTIONPACKAGEANSWERFILE"
   (	"ACTION_PACKAGE_ID" NUMBER NOT NULL ENABLE,
	"ANSWERFILE" BLOB,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNACTIONPACKAGEANSWERFILE" ADD CONSTRAINT "RHN_ACT_P_AF_APID_FK" FOREIGN KEY ("ACTION_PACKAGE_ID")
	  REFERENCES "SPACEUSER"."RHNACTIONPACKAGE" ("ID") ON DELETE CASCADE ENABLE;
