-- created by Oraschemadoc Wed Jan  9 15:06:55 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCHANNELPRODUCT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"PRODUCT" VARCHAR2(256) NOT NULL ENABLE,
	"VERSION" VARCHAR2(64) NOT NULL ENABLE,
	"BETA" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCHANNELPRODUCT" ADD CONSTRAINT "RHN_CHANNELPROD_BETA_CK" CHECK (beta in ('Y', 'N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHANNELPRODUCT" ADD CONSTRAINT "RHN_CHANNELPROD_ID_PK" PRIMARY KEY ("ID") ENABLE;
