-- created by Oraschemadoc Wed Jan  9 15:06:55 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCHANNELFAMILYMEMBERS"
   (	"CHANNEL_ID" NUMBER NOT NULL ENABLE,
	"CHANNEL_FAMILY_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCHANNELFAMILYMEMBERS" ADD CONSTRAINT "RHN_CF_MEMBERS_C_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "SPACEUSER"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHANNELFAMILYMEMBERS" ADD CONSTRAINT "RHN_CF_FAMILY_FK" FOREIGN KEY ("CHANNEL_FAMILY_ID")
	  REFERENCES "SPACEUSER"."RHNCHANNELFAMILY" ("ID") ENABLE;
