-- created by Oraschemadoc Wed Jan  9 15:06:55 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCLIENTCAPABILITY"
   (	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"CAPABILITY_NAME_ID" NUMBER NOT NULL ENABLE,
	"VERSION" VARCHAR2(32) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCLIENTCAPABILITY" ADD CONSTRAINT "RHN_CLIENTCAP_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCLIENTCAPABILITY" ADD CONSTRAINT "RHN_CLIENTCAP_CAP_NID_FK" FOREIGN KEY ("CAPABILITY_NAME_ID")
	  REFERENCES "SPACEUSER"."RHNCLIENTCAPABILITYNAME" ("ID") ENABLE;
