-- created by Oraschemadoc Wed Jan  9 15:06:56 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCONFIGINFO"
   (	"ID" NUMBER NOT NULL ENABLE,
	"USERNAME" VARCHAR2(32),
	"GROUPNAME" VARCHAR2(32),
	"FILEMODE" NUMBER,
	"SYMLINK_TARGET_FILENAME_ID" NUMBER,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"SELINUX_CTX" VARCHAR2(64)
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCONFIGINFO" ADD CONSTRAINT "RHN_CONFINFO_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONFIGINFO" ADD CONSTRAINT "RHN_CONFINFO_SYMLINK_FK" FOREIGN KEY ("SYMLINK_TARGET_FILENAME_ID")
	  REFERENCES "SPACEUSER"."RHNCONFIGFILENAME" ("ID") ENABLE;
