-- created by Oraschemadoc Wed Jan  9 15:06:55 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCHANNELNEWESTPACKAGE"
   (	"CHANNEL_ID" NUMBER NOT NULL ENABLE,
	"NAME_ID" NUMBER NOT NULL ENABLE,
	"EVR_ID" NUMBER NOT NULL ENABLE,
	"PACKAGE_ARCH_ID" NUMBER NOT NULL ENABLE,
	"PACKAGE_ID" NUMBER NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCHANNELNEWESTPACKAGE" ADD CONSTRAINT "RHN_CNP_CID_NID_UQ" UNIQUE ("CHANNEL_ID", "NAME_ID", "PACKAGE_ARCH_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHANNELNEWESTPACKAGE" ADD CONSTRAINT "RHN_CNP_CID_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "SPACEUSER"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHANNELNEWESTPACKAGE" ADD CONSTRAINT "RHN_CNP_NID_FK" FOREIGN KEY ("NAME_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGENAME" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHANNELNEWESTPACKAGE" ADD CONSTRAINT "RHN_CNP_EID_FK" FOREIGN KEY ("EVR_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEEVR" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHANNELNEWESTPACKAGE" ADD CONSTRAINT "RHN_CNP_PAID_FK" FOREIGN KEY ("PACKAGE_ARCH_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEARCH" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHANNELNEWESTPACKAGE" ADD CONSTRAINT "RHN_CNP_PID_FK" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGE" ("ID") ON DELETE CASCADE ENABLE;
