-- created by Oraschemadoc Wed Jan  9 15:06:56 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCONTENTSOURCESSL"
   (	"CONTENT_SOURCE_ID" NUMBER NOT NULL ENABLE,
	"SSL_CA_CERT_ID" NUMBER NOT NULL ENABLE,
	"SSL_CLIENT_CERT_ID" NUMBER,
	"SSL_CLIENT_KEY_ID" NUMBER,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCONTENTSOURCESSL" ADD CONSTRAINT "RHN_CSSSL_CLIENT_CHK" CHECK (ssl_client_key_id is null or ssl_client_cert_id is not null) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONTENTSOURCESSL" ADD CONSTRAINT "RHN_CSSSL_CSID_FK" FOREIGN KEY ("CONTENT_SOURCE_ID")
	  REFERENCES "SPACEUSER"."RHNCONTENTSOURCE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONTENTSOURCESSL" ADD CONSTRAINT "RHN_CSSSL_CACERTID_FK" FOREIGN KEY ("SSL_CA_CERT_ID")
	  REFERENCES "SPACEUSER"."RHNCRYPTOKEY" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONTENTSOURCESSL" ADD CONSTRAINT "RHN_CSSSL_CLCERTID_FK" FOREIGN KEY ("SSL_CLIENT_CERT_ID")
	  REFERENCES "SPACEUSER"."RHNCRYPTOKEY" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONTENTSOURCESSL" ADD CONSTRAINT "RHN_CSSSL_CLKEYID_FK" FOREIGN KEY ("SSL_CLIENT_KEY_ID")
	  REFERENCES "SPACEUSER"."RHNCRYPTOKEY" ("ID") ON DELETE CASCADE ENABLE;
