-- created by Oraschemadoc Wed Jan  9 15:06:56 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCONTENTSOURCE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ORG_ID" NUMBER,
	"TYPE_ID" NUMBER NOT NULL ENABLE,
	"SOURCE_URL" VARCHAR2(2048) NOT NULL ENABLE,
	"LABEL" VARCHAR2(128) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCONTENTSOURCE" ADD CONSTRAINT "RHN_CS_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONTENTSOURCE" ADD CONSTRAINT "RHN_CS_ORG_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONTENTSOURCE" ADD CONSTRAINT "RHN_CS_TYPE_FK" FOREIGN KEY ("TYPE_ID")
	  REFERENCES "SPACEUSER"."RHNCONTENTSOURCETYPE" ("ID") ENABLE;
