-- created by Oraschemadoc Wed Jan  9 15:06:56 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCONFIGCONTENT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"CONTENTS" BLOB,
	"FILE_SIZE" NUMBER,
	"CHECKSUM_ID" NUMBER NOT NULL ENABLE,
	"IS_BINARY" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"DELIM_START" VARCHAR2(16) NOT NULL ENABLE,
	"DELIM_END" VARCHAR2(16) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCONFIGCONTENT" ADD CONSTRAINT "RHN_CONFCONTENT_ISBIN_CK" CHECK (is_binary in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONFIGCONTENT" ADD CONSTRAINT "RHN_CONFCONTENT_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONFIGCONTENT" ADD CONSTRAINT "RHN_CONFCONTENT_CHSUM_FK" FOREIGN KEY ("CHECKSUM_ID")
	  REFERENCES "SPACEUSER"."RHNCHECKSUM" ("ID") ENABLE;
