-- created by Oraschemadoc Wed Jan  9 15:06:56 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCONFIGURATION"
   (	"KEY" VARCHAR2(64) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(512) NOT NULL ENABLE,
	"VALUE" VARCHAR2(512),
	"DEFAULT_VALUE" VARCHAR2(512),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCONFIGURATION" ADD CONSTRAINT "RHNCONFIG_KEY_PK" PRIMARY KEY ("KEY") ENABLE;
