-- created by Oraschemadoc Wed Jan  9 15:06:55 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCHANNELCONTENTSOURCE"
   (	"SOURCE_ID" NUMBER NOT NULL ENABLE,
	"CHANNEL_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCHANNELCONTENTSOURCE" ADD CONSTRAINT "RHN_CCS_UQ" UNIQUE ("SOURCE_ID", "CHANNEL_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHANNELCONTENTSOURCE" ADD CONSTRAINT "RHN_CCS_SRC_ID_FK" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SPACEUSER"."RHNCONTENTSOURCE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHANNELCONTENTSOURCE" ADD CONSTRAINT "RHN_CCS_CID_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "SPACEUSER"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE;
