-- created by Oraschemadoc Wed Jan  9 15:06:56 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCPU"
   (	"ID" NUMBER NOT NULL ENABLE,
	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"CPU_ARCH_ID" NUMBER NOT NULL ENABLE,
	"BOGOMIPS" VARCHAR2(16),
	"CACHE" VARCHAR2(16),
	"FAMILY" VARCHAR2(32),
	"MHZ" VARCHAR2(16),
	"STEPPING" VARCHAR2(16),
	"FLAGS" VARCHAR2(2048),
	"MODEL" VARCHAR2(64),
	"VERSION" VARCHAR2(32),
	"VENDOR" VARCHAR2(32),
	"NRCPU" NUMBER DEFAULT (1),
	"NRSOCKET" NUMBER,
	"ACPIVERSION" VARCHAR2(64),
	"APIC" VARCHAR2(32),
	"APMVERSION" VARCHAR2(32),
	"CHIPSET" VARCHAR2(64),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCPU" ADD CONSTRAINT "RHN_CPU_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCPU" ADD CONSTRAINT "RHN_CPU_SERVER_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCPU" ADD CONSTRAINT "RHN_CPU_CAID_FK" FOREIGN KEY ("CPU_ARCH_ID")
	  REFERENCES "SPACEUSER"."RHNCPUARCH" ("ID") ENABLE;
