-- created by Oraschemadoc Wed Jan  9 15:06:56 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCRYPTOKEY"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ORG_ID" NUMBER,
	"DESCRIPTION" VARCHAR2(1024) NOT NULL ENABLE,
	"CRYPTO_KEY_TYPE_ID" NUMBER NOT NULL ENABLE,
	"KEY" BLOB
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCRYPTOKEY" ADD CONSTRAINT "RHN_CRYPTOKEY_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCRYPTOKEY" ADD CONSTRAINT "RHN_CRYPTOKEY_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCRYPTOKEY" ADD CONSTRAINT "RHN_CRYPTOKEY_CKTID_FK" FOREIGN KEY ("CRYPTO_KEY_TYPE_ID")
	  REFERENCES "SPACEUSER"."RHNCRYPTOKEYTYPE" ("ID") ENABLE;
