-- created by Oraschemadoc Wed Jan  9 15:06:56 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCONFIGCHANNEL"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ORG_ID" NUMBER NOT NULL ENABLE,
	"CONFCHAN_TYPE_ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(128) NOT NULL ENABLE,
	"LABEL" VARCHAR2(64) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(1024) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCONFIGCHANNEL" ADD CONSTRAINT "RHN_CONFCHAN_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONFIGCHANNEL" ADD CONSTRAINT "RHN_CONFCHAN_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONFIGCHANNEL" ADD CONSTRAINT "RHN_CONFCHAN_CTID_FK" FOREIGN KEY ("CONFCHAN_TYPE_ID")
	  REFERENCES "SPACEUSER"."RHNCONFIGCHANNELTYPE" ("ID") ENABLE;
