-- created by Oraschemadoc Wed Jan  9 15:06:55 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCHANNELPACKAGEARCHCOMPAT"
   (	"CHANNEL_ARCH_ID" NUMBER NOT NULL ENABLE,
	"PACKAGE_ARCH_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCHANNELPACKAGEARCHCOMPAT" ADD CONSTRAINT "RHN_CP_AC_CAID_PAID_UQ" UNIQUE ("CHANNEL_ARCH_ID", "PACKAGE_ARCH_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHANNELPACKAGEARCHCOMPAT" ADD CONSTRAINT "RHN_CP_AC_CAID_FK" FOREIGN KEY ("CHANNEL_ARCH_ID")
	  REFERENCES "SPACEUSER"."RHNCHANNELARCH" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHANNELPACKAGEARCHCOMPAT" ADD CONSTRAINT "RHN_CP_AC_PAID_FK" FOREIGN KEY ("PACKAGE_ARCH_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEARCH" ("ID") ENABLE;
