-- created by Oraschemadoc Wed Jan  9 15:06:55 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCHILDCHANNELARCHCOMPAT"
   (	"PARENT_ARCH_ID" NUMBER NOT NULL ENABLE,
	"CHILD_ARCH_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCHILDCHANNELARCHCOMPAT" ADD CONSTRAINT "RHN_CCAC_PAID_CAID_UQ" UNIQUE ("PARENT_ARCH_ID", "CHILD_ARCH_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHILDCHANNELARCHCOMPAT" ADD CONSTRAINT "RHN_CCAC_PAID_FK" FOREIGN KEY ("PARENT_ARCH_ID")
	  REFERENCES "SPACEUSER"."RHNCHANNELARCH" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHILDCHANNELARCHCOMPAT" ADD CONSTRAINT "RHN_CCAC_CAID_FK" FOREIGN KEY ("CHILD_ARCH_ID")
	  REFERENCES "SPACEUSER"."RHNCHANNELARCH" ("ID") ENABLE;
