-- created by Oraschemadoc Wed Jan  9 15:06:56 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCONFIGFILEFAILURE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"LABEL" VARCHAR2(64) NOT NULL ENABLE,
	"NAME" VARCHAR2(256) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCONFIGFILEFAILURE" ADD CONSTRAINT "RHN_CONFFILE_FAIL_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONFIGFILEFAILURE" ADD CONSTRAINT "RHN_CONFFILE_FAIL_LABEL_UQ" UNIQUE ("LABEL") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONFIGFILEFAILURE" ADD CONSTRAINT "RHN_CONFFILE_FAIL_NAME_UQ" UNIQUE ("NAME") ENABLE;
