-- created by Oraschemadoc Wed Jan  9 15:06:57 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCUSTOMDATAKEY"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ORG_ID" NUMBER NOT NULL ENABLE,
	"LABEL" VARCHAR2(64) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(4000) NOT NULL ENABLE,
	"CREATED_BY" NUMBER,
	"LAST_MODIFIED_BY" NUMBER,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCUSTOMDATAKEY" ADD CONSTRAINT "RHN_CDATAKEY_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCUSTOMDATAKEY" ADD CONSTRAINT "RHN_CDATAKEY_OID_LABEL_UQ" UNIQUE ("ORG_ID", "LABEL") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCUSTOMDATAKEY" ADD CONSTRAINT "RHN_CDATAKEY_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCUSTOMDATAKEY" ADD CONSTRAINT "RHN_CDATAKEY_CB_FK" FOREIGN KEY ("CREATED_BY")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCUSTOMDATAKEY" ADD CONSTRAINT "RHN_CDATAKEY_LMB_FK" FOREIGN KEY ("LAST_MODIFIED_BY")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE;
