-- created by Oraschemadoc Wed Jan  9 15:06:54 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCHANNELCLONED"
   (	"ORIGINAL_ID" NUMBER NOT NULL ENABLE,
	"ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCHANNELCLONED" ADD CONSTRAINT "RHN_CHANNELCLONE_FCID_TCID_UQ" UNIQUE ("ORIGINAL_ID", "ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHANNELCLONED" ADD CONSTRAINT "RHN_CHANNELCLONE_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHANNELCLONED" ADD CONSTRAINT "RHN_CHANNELCLONE_FCID_FK" FOREIGN KEY ("ORIGINAL_ID")
	  REFERENCES "SPACEUSER"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHANNELCLONED" ADD CONSTRAINT "RHN_CHANNELCLONE_TCID_FK" FOREIGN KEY ("ID")
	  REFERENCES "SPACEUSER"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE;
