-- created by Oraschemadoc Wed Jan  9 15:06:55 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCLIENTCAPABILITYNAME"
   (	"ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(32) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCLIENTCAPABILITYNAME" ADD CONSTRAINT "RHN_CLIENTCAPNAM_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCLIENTCAPABILITYNAME" ADD CONSTRAINT "RHN_CLIENTCAPNAM_NAME_UNQ" UNIQUE ("NAME") ENABLE;
