-- created by Oraschemadoc Wed Jan  9 15:06:56 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCONFIGREVISION"
   (	"ID" NUMBER NOT NULL ENABLE,
	"REVISION" NUMBER NOT NULL ENABLE,
	"CONFIG_FILE_ID" NUMBER NOT NULL ENABLE,
	"CONFIG_CONTENT_ID" NUMBER,
	"CONFIG_INFO_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"CONFIG_FILE_TYPE_ID" NUMBER DEFAULT (1) NOT NULL ENABLE,
	"CHANGED_BY_ID" NUMBER DEFAULT (null)
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCONFIGREVISION" ADD CONSTRAINT "RHN_CONFREVISION_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONFIGREVISION" ADD CONSTRAINT "RHN_CONFREVISION_CFID_FK" FOREIGN KEY ("CONFIG_FILE_ID")
	  REFERENCES "SPACEUSER"."RHNCONFIGFILE" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONFIGREVISION" ADD CONSTRAINT "RHN_CONFREVISION_CCID_FK" FOREIGN KEY ("CONFIG_CONTENT_ID")
	  REFERENCES "SPACEUSER"."RHNCONFIGCONTENT" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONFIGREVISION" ADD CONSTRAINT "RHN_CONFREVISION_CIID_FK" FOREIGN KEY ("CONFIG_INFO_ID")
	  REFERENCES "SPACEUSER"."RHNCONFIGINFO" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONFIGREVISION" ADD CONSTRAINT "RHN_CONF_REV_CFTI_FK" FOREIGN KEY ("CONFIG_FILE_TYPE_ID")
	  REFERENCES "SPACEUSER"."RHNCONFIGFILETYPE" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCONFIGREVISION" ADD CONSTRAINT "RHN_CONFREVISION_CID_FK" FOREIGN KEY ("CHANGED_BY_ID")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ENABLE;
