-- created by Oraschemadoc Wed Jan  9 15:06:55 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNCHECKSUM"
   (	"ID" NUMBER NOT NULL ENABLE,
	"CHECKSUM_TYPE_ID" NUMBER NOT NULL ENABLE,
	"CHECKSUM" VARCHAR2(128) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNCHECKSUM" ADD CONSTRAINT "RHNCHECKSUM_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHECKSUM" ADD CONSTRAINT "RHNCHECKSUM_CHSUM_UQ" UNIQUE ("CHECKSUM", "CHECKSUM_TYPE_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNCHECKSUM" ADD CONSTRAINT "RHNCHECKSUM_TYPEID_FK" FOREIGN KEY ("CHECKSUM_TYPE_ID")
	  REFERENCES "SPACEUSER"."RHNCHECKSUMTYPE" ("ID") ENABLE;
