-- created by Oraschemadoc Wed Jan  9 15:06:57 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNDEVICE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"CLASS" VARCHAR2(16),
	"BUS" VARCHAR2(16),
	"DETACHED" NUMBER,
	"DEVICE" VARCHAR2(256),
	"DRIVER" VARCHAR2(256),
	"DESCRIPTION" VARCHAR2(256),
	"PCITYPE" NUMBER DEFAULT (-1),
	"PROP1" VARCHAR2(256),
	"PROP2" VARCHAR2(256),
	"PROP3" VARCHAR2(256),
	"PROP4" VARCHAR2(256),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNDEVICE" ADD CONSTRAINT "RHN_DEVICE_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNDEVICE" ADD CONSTRAINT "RHN_DEVICE_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ON DELETE CASCADE ENABLE;
