-- created by Oraschemadoc Wed Jan  9 15:06:57 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNDISTCHANNELMAP"
   (	"ID" NUMBER NOT NULL ENABLE,
	"OS" VARCHAR2(64) NOT NULL ENABLE,
	"RELEASE" VARCHAR2(64) NOT NULL ENABLE,
	"CHANNEL_ARCH_ID" NUMBER NOT NULL ENABLE,
	"CHANNEL_ID" NUMBER NOT NULL ENABLE,
	"ORG_ID" NUMBER
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNDISTCHANNELMAP" ADD CONSTRAINT "RHN_DCM_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNDISTCHANNELMAP" ADD CONSTRAINT "RHN_DCM_RELEASE_CAID_OID_UQ" UNIQUE ("RELEASE", "CHANNEL_ARCH_ID", "ORG_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNDISTCHANNELMAP" ADD CONSTRAINT "RHN_DCM_CAID_FK" FOREIGN KEY ("CHANNEL_ARCH_ID")
	  REFERENCES "SPACEUSER"."RHNCHANNELARCH" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNDISTCHANNELMAP" ADD CONSTRAINT "RHN_DCM_CID_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "SPACEUSER"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNDISTCHANNELMAP" ADD CONSTRAINT "RHN_DCM_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE;
