-- created by Oraschemadoc Wed Jan  9 15:06:57 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNDAILYSUMMARYQUEUE"
   (	"ORG_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNDAILYSUMMARYQUEUE" ADD CONSTRAINT "RHN_DSQUEUE_OID_UQ" UNIQUE ("ORG_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNDAILYSUMMARYQUEUE" ADD CONSTRAINT "RHN_DSQUEUE_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ENABLE;
