-- created by Oraschemadoc Wed Jan  9 15:06:57 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNERRATABUGLISTTMP"
   (	"ERRATA_ID" NUMBER NOT NULL ENABLE,
	"BUG_ID" NUMBER NOT NULL ENABLE,
	"SUMMARY" VARCHAR2(4000),
	"HREF" VARCHAR2(255),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNERRATABUGLISTTMP" ADD CONSTRAINT "RHN_ERRATA_BUGLISTTMP_EID_FK" FOREIGN KEY ("ERRATA_ID")
	  REFERENCES "SPACEUSER"."RHNERRATATMP" ("ID") ON DELETE CASCADE ENABLE;
