-- created by Oraschemadoc Wed Jan  9 15:06:57 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNERRATACLONEDTMP"
   (	"ORIGINAL_ID" NUMBER NOT NULL ENABLE,
	"ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNERRATACLONEDTMP" ADD CONSTRAINT "RHN_ECLONEDTMP_FEID_TEID_UQ" UNIQUE ("ORIGINAL_ID", "ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATACLONEDTMP" ADD CONSTRAINT "RHN_ECLONEDTMP_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATACLONEDTMP" ADD CONSTRAINT "RHN_ECLONEDTMP_FEID_FK" FOREIGN KEY ("ORIGINAL_ID")
	  REFERENCES "SPACEUSER"."RHNERRATA" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATACLONEDTMP" ADD CONSTRAINT "RHN_ECLONEDTMP_TEID_FK" FOREIGN KEY ("ID")
	  REFERENCES "SPACEUSER"."RHNERRATATMP" ("ID") ON DELETE CASCADE ENABLE;
