-- created by Oraschemadoc Wed Jan  9 15:06:58 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNERRATANOTIFICATIONQUEUE"
   (	"ERRATA_ID" NUMBER NOT NULL ENABLE,
	"ORG_ID" NUMBER NOT NULL ENABLE,
	"NEXT_ACTION" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp),
	"CHANNEL_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNERRATANOTIFICATIONQUEUE" ADD CONSTRAINT "RHN_ENQUEUE_EOID_UQ" UNIQUE ("ERRATA_ID", "CHANNEL_ID", "ORG_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATANOTIFICATIONQUEUE" ADD CONSTRAINT "RHN_ENQUEUE_EID_FK" FOREIGN KEY ("ERRATA_ID")
	  REFERENCES "SPACEUSER"."RHNERRATA" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATANOTIFICATIONQUEUE" ADD CONSTRAINT "RHN_ENQUEUE_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATANOTIFICATIONQUEUE" ADD CONSTRAINT "RHN_ENQUEUE_CID_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "SPACEUSER"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE;
