-- created by Oraschemadoc Wed Jan  9 15:06:58 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNERRATAFILEPACKAGETMP"
   (	"PACKAGE_ID" NUMBER NOT NULL ENABLE,
	"ERRATA_FILE_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILEPACKAGETMP" ADD CONSTRAINT "RHN_EFILEPTMP_EFID_UQ" UNIQUE ("ERRATA_FILE_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILEPACKAGETMP" ADD CONSTRAINT "RHN_EFILEPTMP_PID_FK" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILEPACKAGETMP" ADD CONSTRAINT "RHN_EFILEPTMP_FILEID_FK" FOREIGN KEY ("ERRATA_FILE_ID")
	  REFERENCES "SPACEUSER"."RHNERRATAFILETMP" ("ID") ON DELETE CASCADE ENABLE;
