-- created by Oraschemadoc Wed Jan  9 15:06:57 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNERRATACVE"
   (	"ERRATA_ID" NUMBER NOT NULL ENABLE,
	"CVE_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNERRATACVE" ADD CONSTRAINT "RHN_ERR_CVE_EID_FK" FOREIGN KEY ("ERRATA_ID")
	  REFERENCES "SPACEUSER"."RHNERRATA" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATACVE" ADD CONSTRAINT "RHN_ERR_CVE_CID_FK" FOREIGN KEY ("CVE_ID")
	  REFERENCES "SPACEUSER"."RHNCVE" ("ID") ENABLE;
