-- created by Oraschemadoc Wed Jan  9 15:06:57 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNERRATAFILE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ERRATA_ID" NUMBER NOT NULL ENABLE,
	"TYPE" NUMBER NOT NULL ENABLE,
	"CHECKSUM_ID" NUMBER NOT NULL ENABLE,
	"FILENAME" VARCHAR2(4000) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILE" ADD CONSTRAINT "RHN_ERRATAFILE_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILE" ADD CONSTRAINT "RHN_ERRATAFILE_EID_FILE_UQ" UNIQUE ("ERRATA_ID", "FILENAME") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILE" ADD CONSTRAINT "RHN_ERRATAFILE_ERRATA_FK" FOREIGN KEY ("ERRATA_ID")
	  REFERENCES "SPACEUSER"."RHNERRATA" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILE" ADD CONSTRAINT "RHN_ERRATAFILE_TYPE_FK" FOREIGN KEY ("TYPE")
	  REFERENCES "SPACEUSER"."RHNERRATAFILETYPE" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILE" ADD CONSTRAINT "RHN_ERRATAFILE_CHSUM_FK" FOREIGN KEY ("CHECKSUM_ID")
	  REFERENCES "SPACEUSER"."RHNCHECKSUM" ("ID") ENABLE;
