-- created by Oraschemadoc Wed Jan  9 15:06:57 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNERRATAFILECHANNEL"
   (	"CHANNEL_ID" NUMBER NOT NULL ENABLE,
	"ERRATA_FILE_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILECHANNEL" ADD CONSTRAINT "RHN_EFILEC_EFID_CID_UQ" UNIQUE ("ERRATA_FILE_ID", "CHANNEL_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILECHANNEL" ADD CONSTRAINT "RHN_EFILEC_CID_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "SPACEUSER"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILECHANNEL" ADD CONSTRAINT "RHN_EFILEC_EID_FK" FOREIGN KEY ("ERRATA_FILE_ID")
	  REFERENCES "SPACEUSER"."RHNERRATAFILE" ("ID") ON DELETE CASCADE ENABLE;
