-- created by Oraschemadoc Wed Jan  9 15:06:57 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNERRATAFILEPACKAGESOURCE"
   (	"PACKAGE_ID" NUMBER NOT NULL ENABLE,
	"ERRATA_FILE_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILEPACKAGESOURCE" ADD CONSTRAINT "RHN_EFILEPS_EFID_UQ" UNIQUE ("ERRATA_FILE_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILEPACKAGESOURCE" ADD CONSTRAINT "RHN_EFILEPS_PID_FK" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGESOURCE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILEPACKAGESOURCE" ADD CONSTRAINT "RHN_EFILEPS_FILEID_FK" FOREIGN KEY ("ERRATA_FILE_ID")
	  REFERENCES "SPACEUSER"."RHNERRATAFILE" ("ID") ON DELETE CASCADE ENABLE;
