-- created by Oraschemadoc Wed Jan  9 15:06:58 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNERRATAFILETYPE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"LABEL" VARCHAR2(128) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILETYPE" ADD CONSTRAINT "RHN_ERRATAFILE_TYPE_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILETYPE" ADD CONSTRAINT "RHN_ERRATAFILE_TYPE_LABEL_UQ" UNIQUE ("LABEL") ENABLE;
