-- created by Oraschemadoc Wed Jan  9 15:06:57 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNERRATAFILEPACKAGE"
   (	"PACKAGE_ID" NUMBER NOT NULL ENABLE,
	"ERRATA_FILE_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILEPACKAGE" ADD CONSTRAINT "RHN_EFILEP_EFID_UQ" UNIQUE ("ERRATA_FILE_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILEPACKAGE" ADD CONSTRAINT "RHN_EFILEP_PID_FK" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNERRATAFILEPACKAGE" ADD CONSTRAINT "RHN_EFILEP_FILEID_FK" FOREIGN KEY ("ERRATA_FILE_ID")
	  REFERENCES "SPACEUSER"."RHNERRATAFILE" ("ID") ON DELETE CASCADE ENABLE;
