-- created by Oraschemadoc Wed Jan  9 15:06:58 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNERRATASEVERITY"
   (	"ID" NUMBER NOT NULL ENABLE,
	"RANK" NUMBER NOT NULL ENABLE,
	"LABEL" VARCHAR2(40) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNERRATASEVERITY" ADD CONSTRAINT "RHN_ERRATA_SEV_ID_PK" PRIMARY KEY ("ID") ENABLE;
