-- created by Oraschemadoc Wed Jan  9 15:06:58 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNFILEDOWNLOAD"
   (	"FILE_ID" NUMBER NOT NULL ENABLE,
	"LOCATION" VARCHAR2(2000) NOT NULL ENABLE,
	"TOKEN" VARCHAR2(48),
	"REQUESTOR_IP" VARCHAR2(15) NOT NULL ENABLE,
	"START_TIME" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"USER_ID" NUMBER
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNFILEDOWNLOAD" ADD CONSTRAINT "RHN_FILEDL_FID_FK" FOREIGN KEY ("FILE_ID")
	  REFERENCES "SPACEUSER"."RHNFILE" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNFILEDOWNLOAD" ADD CONSTRAINT "RHN_FILEDL_UID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE;
