-- created by Oraschemadoc Wed Jan  9 15:06:58 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNFILELOCATION"
   (	"FILE_ID" NUMBER NOT NULL ENABLE,
	"LOCATION" VARCHAR2(128) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNFILELOCATION" ADD CONSTRAINT "RHN_FILELOC_FID_FK" FOREIGN KEY ("FILE_ID")
	  REFERENCES "SPACEUSER"."RHNFILE" ("ID") ENABLE;
