-- created by Oraschemadoc Wed Jan  9 15:06:59 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNISSMASTER"
   (	"ID" NUMBER NOT NULL ENABLE,
	"LABEL" VARCHAR2(256) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"IS_CURRENT_MASTER" CHAR(1) DEFAULT 'N' NOT NULL ENABLE,
	"CA_CERT" VARCHAR2(1024)
   ) ;
  ALTER TABLE "SPACEUSER"."RHNISSMASTER" ADD CONSTRAINT "RHN_ISSM_MASTER_YN" CHECK (is_current_master in ('Y', 'N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNISSMASTER" ADD CONSTRAINT "RHN_ISS_MASTER_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNISSMASTER" ADD CONSTRAINT "RHN_ISS_MASTER_LABEL_UQ" UNIQUE ("LABEL") ENABLE;
