-- created by Oraschemadoc Wed Jan  9 15:06:59 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNISSSLAVE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"SLAVE" VARCHAR2(512) NOT NULL ENABLE,
	"ENABLED" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"ALLOW_ALL_ORGS" CHAR(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ;
  ALTER TABLE "SPACEUSER"."RHNISSSLAVE" ADD CONSTRAINT "RHN_ISSS_ENABLED_YN" CHECK (enabled in ( 'Y', 'N' )) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNISSSLAVE" ADD CONSTRAINT "RHN_ISSS_ALLORGS_YN" CHECK (allow_all_orgs in ( 'Y', 'N' )) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNISSSLAVE" ADD CONSTRAINT "RHN_ISSS_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNISSSLAVE" ADD CONSTRAINT "RHN_ISSS_NAME_UQ" UNIQUE ("SLAVE") ENABLE;
