-- created by Oraschemadoc Wed Jan  9 15:06:59 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNISSMASTERORGS"
   (	"ID" NUMBER NOT NULL ENABLE,
	"MASTER_ID" NUMBER NOT NULL ENABLE,
	"MASTER_ORG_ID" NUMBER NOT NULL ENABLE,
	"MASTER_ORG_NAME" VARCHAR2(512) NOT NULL ENABLE,
	"LOCAL_ORG_ID" NUMBER,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ;
  ALTER TABLE "SPACEUSER"."RHNISSMASTERORGS" ADD CONSTRAINT "RHN_ISSMASTERORGS_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNISSMASTERORGS" ADD CONSTRAINT "RHN_ISSMASTERORGS_CID_FK" FOREIGN KEY ("MASTER_ID")
	  REFERENCES "SPACEUSER"."RHNISSMASTER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNISSMASTERORGS" ADD CONSTRAINT "RHN_ISSMASTERORGS_LID_FK" FOREIGN KEY ("LOCAL_ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ENABLE;
