-- created by Oraschemadoc Wed Jan  9 15:06:59 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNKICKSTARTIPRANGE"
   (	"KICKSTART_ID" NUMBER NOT NULL ENABLE,
	"ORG_ID" NUMBER NOT NULL ENABLE,
	"MIN" NUMBER NOT NULL ENABLE,
	"MAX" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTIPRANGE" ADD CONSTRAINT "RHN_KSIP_OID_MIN_MAX_UQ" UNIQUE ("ORG_ID", "MIN", "MAX") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTIPRANGE" ADD CONSTRAINT "RHN_KSIP_KSID_FK" FOREIGN KEY ("KICKSTART_ID")
	  REFERENCES "SPACEUSER"."RHNKSDATA" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTIPRANGE" ADD CONSTRAINT "RHN_KSIP_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE;
