-- created by Oraschemadoc Wed Jan  9 15:07:00 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNKICKSTARTVIRTUALIZATIONTYPE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(128) NOT NULL ENABLE,
	"LABEL" VARCHAR2(128) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTVIRTUALIZATIONTYPE" ADD CONSTRAINT "RHN_KVT_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTVIRTUALIZATIONTYPE" ADD CONSTRAINT "RHN_KVT_LABEL_UNQ" UNIQUE ("LABEL") ENABLE;
