-- created by Oraschemadoc Wed Jan  9 15:07:00 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNKICKSTARTTIMEZONE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"LABEL" VARCHAR2(128) NOT NULL ENABLE,
	"NAME" VARCHAR2(128) NOT NULL ENABLE,
	"INSTALL_TYPE" NUMBER NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTTIMEZONE" ADD CONSTRAINT "RHN_KS_TIMEZONE_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTTIMEZONE" ADD CONSTRAINT "RHN_KS_TIMEZONE_IT_FK" FOREIGN KEY ("INSTALL_TYPE")
	  REFERENCES "SPACEUSER"."RHNKSINSTALLTYPE" ("ID") ENABLE;
