-- created by Oraschemadoc Wed Jan  9 15:06:59 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNKICKSTARTCOMMAND"
   (	"ID" NUMBER,
	"KICKSTART_ID" NUMBER NOT NULL ENABLE,
	"KS_COMMAND_NAME_ID" NUMBER NOT NULL ENABLE,
	"ARGUMENTS" VARCHAR2(2048),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"CUSTOM_POSITION" NUMBER
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTCOMMAND" ADD CONSTRAINT "RHN_KSCOMMAND_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTCOMMAND" ADD CONSTRAINT "RHN_KSCOMMAND_KSID_FK" FOREIGN KEY ("KICKSTART_ID")
	  REFERENCES "SPACEUSER"."RHNKSDATA" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTCOMMAND" ADD CONSTRAINT "RHN_KSCOMMAND_KCNID_FK" FOREIGN KEY ("KS_COMMAND_NAME_ID")
	  REFERENCES "SPACEUSER"."RHNKICKSTARTCOMMANDNAME" ("ID") ENABLE;
