-- created by Oraschemadoc Wed Jan  9 15:06:59 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNKICKSTARTDEFAULTS"
   (	"KICKSTART_ID" NUMBER NOT NULL ENABLE,
	"KSTREE_ID" NUMBER NOT NULL ENABLE,
	"SERVER_PROFILE_ID" NUMBER,
	"CFG_MANAGEMENT_FLAG" CHAR(1) DEFAULT ('Y') NOT NULL ENABLE,
	"REMOTE_COMMAND_FLAG" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"VIRTUALIZATION_TYPE" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTDEFAULTS" ADD CONSTRAINT "RHN_KSD_CMF_CK" CHECK (cfg_management_flag in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTDEFAULTS" ADD CONSTRAINT "RHN_KSD_RMF_CK" CHECK (remote_command_flag in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTDEFAULTS" ADD CONSTRAINT "RHN_KSD_KSID_UQ" UNIQUE ("KICKSTART_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTDEFAULTS" ADD CONSTRAINT "RHN_KSD_KSID_FK" FOREIGN KEY ("KICKSTART_ID")
	  REFERENCES "SPACEUSER"."RHNKSDATA" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTDEFAULTS" ADD CONSTRAINT "RHN_KSD_KSTID_FK" FOREIGN KEY ("KSTREE_ID")
	  REFERENCES "SPACEUSER"."RHNKICKSTARTABLETREE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTDEFAULTS" ADD CONSTRAINT "RHN_KSD_SPID_FK" FOREIGN KEY ("SERVER_PROFILE_ID")
	  REFERENCES "SPACEUSER"."RHNSERVERPROFILE" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTDEFAULTS" ADD CONSTRAINT "RHN_KSD_KVT_FK" FOREIGN KEY ("VIRTUALIZATION_TYPE")
	  REFERENCES "SPACEUSER"."RHNKICKSTARTVIRTUALIZATIONTYPE" ("ID") ON DELETE SET NULL ENABLE;
