-- created by Oraschemadoc Wed Jan  9 15:06:59 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNKICKSTARTSCRIPT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"SCRIPT_NAME" VARCHAR2(40),
	"KICKSTART_ID" NUMBER NOT NULL ENABLE,
	"POSITION" NUMBER NOT NULL ENABLE,
	"SCRIPT_TYPE" VARCHAR2(4) NOT NULL ENABLE,
	"CHROOT" CHAR(1) DEFAULT ('Y') NOT NULL ENABLE,
	"ERROR_ON_FAIL" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"RAW_SCRIPT" CHAR(1) DEFAULT ('Y') NOT NULL ENABLE,
	"INTERPRETER" VARCHAR2(80),
	"DATA" BLOB,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTSCRIPT" ADD CONSTRAINT "RHN_KSSCRIPT_ST_CK" CHECK (script_type in ('pre','post')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTSCRIPT" ADD CONSTRAINT "RHN_KSSCRIPT_CHROOT_CK" CHECK (chroot in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTSCRIPT" ADD CONSTRAINT "RHN_KSSCRIPT_ERRORONFAIL_CK" CHECK (error_on_fail in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTSCRIPT" ADD CONSTRAINT "RHN_KSSCRIPT_RAWSCRIPT_CK" CHECK (raw_script in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTSCRIPT" ADD CONSTRAINT "RHN_KSSCRIPT_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTSCRIPT" ADD CONSTRAINT "RHN_KSSCRIPT_KSID_POS_UQ" UNIQUE ("KICKSTART_ID", "POSITION") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTSCRIPT" ADD CONSTRAINT "RHN_KSSCRIPT_KSID_FK" FOREIGN KEY ("KICKSTART_ID")
	  REFERENCES "SPACEUSER"."RHNKSDATA" ("ID") ON DELETE CASCADE ENABLE;
