-- created by Oraschemadoc Wed Jan  9 15:07:00 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNKSDATA"
   (	"ID" NUMBER NOT NULL ENABLE,
	"KS_TYPE" VARCHAR2(8) NOT NULL ENABLE,
	"ORG_ID" NUMBER NOT NULL ENABLE,
	"IS_ORG_DEFAULT" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"LABEL" VARCHAR2(64) NOT NULL ENABLE,
	"COMMENTS" VARCHAR2(4000),
	"ACTIVE" CHAR(1) DEFAULT ('Y') NOT NULL ENABLE,
	"POSTLOG" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"PRELOG" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"KSCFG" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"COBBLER_ID" VARCHAR2(64),
	"PRE" BLOB,
	"POST" BLOB,
	"NOCHROOT_POST" BLOB,
	"PARTITION_DATA" BLOB,
	"STATIC_DEVICE" VARCHAR2(32),
	"KERNEL_PARAMS" VARCHAR2(128),
	"VERBOSEUP2DATE" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"NONCHROOTPOST" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"NO_BASE" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"IGNORE_MISSING" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"UPDATE_TYPE" VARCHAR2(7) DEFAULT ('none') NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNKSDATA" ADD CONSTRAINT "RHN_KS_DEFAULT_CK" CHECK (is_org_default in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKSDATA" ADD CONSTRAINT "RHN_KS_ACTIVE_CK" CHECK (active in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKSDATA" ADD CONSTRAINT "RHN_KS_POST_LOG_CK" CHECK (postLog in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKSDATA" ADD CONSTRAINT "RHN_KS_PRE_LOG_CK" CHECK (preLog in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKSDATA" ADD CONSTRAINT "RHN_KS_CFG_SAVE_CK" CHECK (kscfg in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKSDATA" ADD CONSTRAINT "RHN_KS_VERBOSE_UP2DATE_CK" CHECK (verboseup2date in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKSDATA" ADD CONSTRAINT "RHN_KS_NONCHROOT_POST_CK" CHECK (nonchrootpost in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKSDATA" ADD CONSTRAINT "RHN_KS_NOBASE_CK" CHECK (no_base in ( 'Y' , 'N' )) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKSDATA" ADD CONSTRAINT "RHN_KS_IGNORE_MISSING_CK" CHECK (ignore_missing in ( 'Y' , 'N' )) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKSDATA" ADD CONSTRAINT "RHN_KS_UPDATE_TYPE" CHECK (update_type in ('all', 'red_hat', 'none')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKSDATA" ADD CONSTRAINT "RHN_KS_TYPE_CK" CHECK (ks_type in ('wizard','raw')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKSDATA" ADD CONSTRAINT "RHN_KS_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKSDATA" ADD CONSTRAINT "RHN_KS_OID_LABEL_UQ" UNIQUE ("ORG_ID", "LABEL") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKSDATA" ADD CONSTRAINT "RHN_KS_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE;
