-- created by Oraschemadoc Wed Jan  9 15:07:00 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNKICKSTARTSESSIONSTATE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"LABEL" VARCHAR2(64) NOT NULL ENABLE,
	"NAME" VARCHAR2(128) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(1024) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTSESSIONSTATE" ADD CONSTRAINT "RHN_KS_SESSION_STATE_ID_PK" PRIMARY KEY ("ID") ENABLE;
