-- created by Oraschemadoc Wed Jan  9 15:06:59 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNKICKSTARTABLETREE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ORG_ID" NUMBER,
	"LABEL" VARCHAR2(64) NOT NULL ENABLE,
	"BASE_PATH" VARCHAR2(256) NOT NULL ENABLE,
	"CHANNEL_ID" NUMBER NOT NULL ENABLE,
	"COBBLER_ID" VARCHAR2(64),
	"COBBLER_XEN_ID" VARCHAR2(64),
	"BOOT_IMAGE" VARCHAR2(128) DEFAULT ('spacewalk-koan'),
	"KSTREE_TYPE" NUMBER NOT NULL ENABLE,
	"INSTALL_TYPE" NUMBER NOT NULL ENABLE,
	"KERNEL_OPTIONS" VARCHAR2(256),
	"KERNEL_OPTIONS_POST" VARCHAR2(256),
	"LAST_MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTABLETREE" ADD CONSTRAINT "RHN_KSTREE_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTABLETREE" ADD CONSTRAINT "RHN_KSTREE_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTABLETREE" ADD CONSTRAINT "RHN_KSTREE_CID_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "SPACEUSER"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTABLETREE" ADD CONSTRAINT "RHN_KSTREE_KSTREETYPE_FK" FOREIGN KEY ("KSTREE_TYPE")
	  REFERENCES "SPACEUSER"."RHNKSTREETYPE" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTABLETREE" ADD CONSTRAINT "RHN_KSTREE_IT_FK" FOREIGN KEY ("INSTALL_TYPE")
	  REFERENCES "SPACEUSER"."RHNKSINSTALLTYPE" ("ID") ENABLE;
