-- created by Oraschemadoc Wed Jan  9 15:06:59 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNKICKSTARTCOMMANDNAME"
   (	"ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(128) NOT NULL ENABLE,
	"USES_ARGUMENTS" CHAR(1) NOT NULL ENABLE,
	"SORT_ORDER" NUMBER NOT NULL ENABLE,
	"REQUIRED" CHAR(1) DEFAULT ('N') NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTCOMMANDNAME" ADD CONSTRAINT "RHN_KSCOMMANDNAME_USES_ARGS_CK" CHECK (uses_arguments in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTCOMMANDNAME" ADD CONSTRAINT "RHN_KSCOMMANDNAME_REQRD_CK" CHECK ( required in ('Y', 'N') ) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTCOMMANDNAME" ADD CONSTRAINT "RHN_KSCOMMANDNAME_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTCOMMANDNAME" ADD CONSTRAINT "RHN_KSCOMMANDNAME_NAME_UQ" UNIQUE ("NAME") ENABLE;
