-- created by Oraschemadoc Wed Jan  9 15:06:59 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNKICKSTARTPACKAGE"
   (	"KICKSTART_ID" NUMBER NOT NULL ENABLE,
	"PACKAGE_NAME_ID" NUMBER NOT NULL ENABLE,
	"POSITION" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTPACKAGE" ADD CONSTRAINT "RHN_KSPACKAGE_POS_UQ" UNIQUE ("KICKSTART_ID", "POSITION") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTPACKAGE" ADD CONSTRAINT "RHN_KSPACKAGE_NAME_UQ" UNIQUE ("KICKSTART_ID", "PACKAGE_NAME_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTPACKAGE" ADD CONSTRAINT "RHN_KSPACKAGE_KSID_FK" FOREIGN KEY ("KICKSTART_ID")
	  REFERENCES "SPACEUSER"."RHNKSDATA" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNKICKSTARTPACKAGE" ADD CONSTRAINT "RHN_KSPACKAGE_PNID_FK" FOREIGN KEY ("PACKAGE_NAME_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGENAME" ("ID") ENABLE;
