-- created by Oraschemadoc Wed Jan  9 15:07:00 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNORGEXTGROUPMAPPING"
   (	"ID" NUMBER NOT NULL ENABLE,
	"EXT_GROUP_ID" NUMBER NOT NULL ENABLE,
	"SERVER_GROUP_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNORGEXTGROUPMAPPING" ADD CONSTRAINT "RHN_ORGEXTGROUPMAP_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNORGEXTGROUPMAPPING" ADD CONSTRAINT "RHN_ORGEXTGROUPMAP_EG_FK" FOREIGN KEY ("EXT_GROUP_ID")
	  REFERENCES "SPACEUSER"."RHNUSEREXTGROUP" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNORGEXTGROUPMAPPING" ADD CONSTRAINT "RHN_ORGEXTGROUPMAP_SG_FK" FOREIGN KEY ("SERVER_GROUP_ID")
	  REFERENCES "SPACEUSER"."RHNSERVERGROUP" ("ID") ON DELETE CASCADE ENABLE;
