-- created by Oraschemadoc Wed Jan  9 15:07:00 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNORGADMINMANAGEMENT"
   (	"ORG_ID" NUMBER NOT NULL ENABLE,
	"ENABLED" CHAR(1) DEFAULT ('Y') NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNORGADMINMANAGEMENT" ADD CONSTRAINT "RHN_ORGADM_MNGT_ENABLED_CK" CHECK (enabled in ('Y', 'N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNORGADMINMANAGEMENT" ADD CONSTRAINT "RHN_ORGADM_MNGT_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE;
