-- created by Oraschemadoc Wed Jan  9 15:07:00 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNORGERRATACACHEQUEUE"
   (	"ORG_ID" NUMBER NOT NULL ENABLE,
	"SERVER_COUNT" NUMBER NOT NULL ENABLE,
	"PROCESSED" NUMBER DEFAULT (0) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNORGERRATACACHEQUEUE" ADD CONSTRAINT "RHN_OECQ_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE;
