-- created by Oraschemadoc Wed Jan  9 15:07:01 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNPACKAGEFILE"
   (	"PACKAGE_ID" NUMBER NOT NULL ENABLE,
	"CAPABILITY_ID" NUMBER NOT NULL ENABLE,
	"DEVICE" NUMBER NOT NULL ENABLE,
	"INODE" NUMBER NOT NULL ENABLE,
	"FILE_MODE" NUMBER NOT NULL ENABLE,
	"USERNAME" VARCHAR2(32) NOT NULL ENABLE,
	"GROUPNAME" VARCHAR2(32) NOT NULL ENABLE,
	"RDEV" NUMBER NOT NULL ENABLE,
	"FILE_SIZE" NUMBER NOT NULL ENABLE,
	"MTIME" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE,
	"CHECKSUM_ID" NUMBER,
	"LINKTO" VARCHAR2(256),
	"FLAGS" NUMBER NOT NULL ENABLE,
	"VERIFYFLAGS" NUMBER NOT NULL ENABLE,
	"LANG" VARCHAR2(32),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNPACKAGEFILE" ADD CONSTRAINT "RHN_PACKAGE_FILE_PID_FK" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGEFILE" ADD CONSTRAINT "RHN_PACKAGE_FILE_CID_FK" FOREIGN KEY ("CAPABILITY_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGECAPABILITY" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGEFILE" ADD CONSTRAINT "RHN_PACKAGE_FILE_CHSUM_FK" FOREIGN KEY ("CHECKSUM_ID")
	  REFERENCES "SPACEUSER"."RHNCHECKSUM" ("ID") ENABLE;
