-- created by Oraschemadoc Wed Jan  9 15:07:01 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNPACKAGEDELTAELEMENT"
   (	"PACKAGE_DELTA_ID" NUMBER NOT NULL ENABLE,
	"TRANSACTION_PACKAGE_ID" NUMBER NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNPACKAGEDELTAELEMENT" ADD CONSTRAINT "RHN_PDELEMENT_PDID_FK" FOREIGN KEY ("PACKAGE_DELTA_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEDELTA" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGEDELTAELEMENT" ADD CONSTRAINT "RHN_PDELEMENT_TPID_FK" FOREIGN KEY ("TRANSACTION_PACKAGE_ID")
	  REFERENCES "SPACEUSER"."RHNTRANSACTIONPACKAGE" ("ID") ENABLE;
