-- created by Oraschemadoc Wed Jan  9 15:07:02 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNPACKAGENEVRA"
   (	"ID" NUMBER NOT NULL ENABLE,
	"NAME_ID" NUMBER NOT NULL ENABLE,
	"EVR_ID" NUMBER NOT NULL ENABLE,
	"PACKAGE_ARCH_ID" NUMBER
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNPACKAGENEVRA" ADD CONSTRAINT "RHN_PKGNEVRA_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGENEVRA" ADD CONSTRAINT "RHN_PKGNEVRA_NID_EID_PAID_UQ" UNIQUE ("NAME_ID", "EVR_ID", "PACKAGE_ARCH_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGENEVRA" ADD CONSTRAINT "RHN_PKGNEVRA_NID_FK" FOREIGN KEY ("NAME_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGENAME" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGENEVRA" ADD CONSTRAINT "RHN_PKGNEVRA_EID_FK" FOREIGN KEY ("EVR_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEEVR" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGENEVRA" ADD CONSTRAINT "RHN_PKGNEVRA_PAID_FK" FOREIGN KEY ("PACKAGE_ARCH_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEARCH" ("ID") ENABLE;
