-- created by Oraschemadoc Wed Jan  9 15:07:01 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNPACKAGEEVR"
   (	"ID" NUMBER NOT NULL ENABLE,
	"EPOCH" VARCHAR2(16),
	"VERSION" VARCHAR2(512) NOT NULL ENABLE,
	"RELEASE" VARCHAR2(512) NOT NULL ENABLE,
	"EVR" "SPACEUSER"."EVR_T"  NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNPACKAGEEVR" ADD CONSTRAINT "RHN_PE_ID_PK" PRIMARY KEY ("ID") ENABLE;
