-- created by Oraschemadoc Wed Jan  9 15:07:02 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNPACKAGEPROVIDER"
   (	"ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(64) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ;
  ALTER TABLE "SPACEUSER"."RHNPACKAGEPROVIDER" ADD CONSTRAINT "RHN_PKG_PROVIDER_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGEPROVIDER" ADD CONSTRAINT "RHN_PKG_PROVIDER_NAME_UQ" UNIQUE ("NAME") ENABLE;
