-- created by Oraschemadoc Wed Jan  9 15:07:01 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNPACKAGECAPABILITY"
   (	"ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(4000) NOT NULL ENABLE,
	"VERSION" VARCHAR2(512),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNPACKAGECAPABILITY" ADD CONSTRAINT "RHN_PKG_CAPABILITY_ID_PK" PRIMARY KEY ("ID") ENABLE;
