-- created by Oraschemadoc Wed Jan  9 15:07:03 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNPUSHDISPATCHER"
   (	"ID" NUMBER NOT NULL ENABLE,
	"JABBER_ID" VARCHAR2(128) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(32),
	"LAST_CHECKIN" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"HOSTNAME" VARCHAR2(256) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNPUSHDISPATCHER" ADD CONSTRAINT "RHN_PUSHDISPATCH_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPUSHDISPATCHER" ADD CONSTRAINT "RHN_PUSHDISPATCH_JID_UQ" UNIQUE ("JABBER_ID") ENABLE;
