-- created by Oraschemadoc Wed Jan  9 15:07:02 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNPROXYINFO"
   (	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"PROXY_EVR_ID" NUMBER
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNPROXYINFO" ADD CONSTRAINT "RHN_PROXY_INFO_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPROXYINFO" ADD CONSTRAINT "RHN_PROXY_INFO_PEID_FK" FOREIGN KEY ("PROXY_EVR_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEEVR" ("ID") ENABLE;
