-- created by Oraschemadoc Wed Jan  9 15:07:01 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNPACKAGECHANGELOGDATA"
   (	"ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(128) NOT NULL ENABLE,
	"TEXT" VARCHAR2(3000) NOT NULL ENABLE,
	"TIME" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNPACKAGECHANGELOGDATA" ADD CONSTRAINT "RHN_PKG_CLD_ID_PK" PRIMARY KEY ("ID") ENABLE;
