-- created by Oraschemadoc Wed Jan  9 15:07:01 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNPACKAGEKEY"
   (	"ID" NUMBER NOT NULL ENABLE,
	"KEY_ID" VARCHAR2(64) NOT NULL ENABLE,
	"KEY_TYPE_ID" NUMBER NOT NULL ENABLE,
	"PROVIDER_ID" NUMBER,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ;
  ALTER TABLE "SPACEUSER"."RHNPACKAGEKEY" ADD CONSTRAINT "RHN_PKEY_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGEKEY" ADD CONSTRAINT "RHN_PKEY_KEYID_UQ" UNIQUE ("KEY_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGEKEY" ADD CONSTRAINT "RHN_PKEY_TYPE_ID_PRID_FK" FOREIGN KEY ("KEY_TYPE_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEKEYTYPE" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGEKEY" ADD CONSTRAINT "RHN_PKEY_PRID_FK" FOREIGN KEY ("PROVIDER_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEPROVIDER" ("ID") ENABLE;
