-- created by Oraschemadoc Wed Jan  9 15:07:01 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNPACKAGE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ORG_ID" NUMBER,
	"NAME_ID" NUMBER NOT NULL ENABLE,
	"EVR_ID" NUMBER NOT NULL ENABLE,
	"PACKAGE_ARCH_ID" NUMBER NOT NULL ENABLE,
	"PACKAGE_GROUP" NUMBER,
	"RPM_VERSION" VARCHAR2(16),
	"DESCRIPTION" VARCHAR2(4000),
	"SUMMARY" VARCHAR2(4000),
	"PACKAGE_SIZE" NUMBER NOT NULL ENABLE,
	"PAYLOAD_SIZE" NUMBER,
	"INSTALLED_SIZE" NUMBER,
	"BUILD_HOST" VARCHAR2(256),
	"BUILD_TIME" TIMESTAMP (6),
	"SOURCE_RPM_ID" NUMBER,
	"CHECKSUM_ID" NUMBER NOT NULL ENABLE,
	"VENDOR" VARCHAR2(64) NOT NULL ENABLE,
	"PAYLOAD_FORMAT" VARCHAR2(32),
	"COMPAT" NUMBER(1,0) DEFAULT (0),
	"PATH" VARCHAR2(1000),
	"HEADER_SIG" VARCHAR2(64),
	"COPYRIGHT" VARCHAR2(128),
	"COOKIE" VARCHAR2(128),
	"LAST_MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"HEADER_START" NUMBER DEFAULT (-1) NOT NULL ENABLE,
	"HEADER_END" NUMBER DEFAULT (-1) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNPACKAGE" ADD CONSTRAINT "RHN_PACKAGE_COMPAT_CHECK" CHECK (compat in ( 1 , 0 )) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGE" ADD CONSTRAINT "RHN_PACKAGE_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGE" ADD CONSTRAINT "RHN_PACKAGE_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGE" ADD CONSTRAINT "RHN_PACKAGE_NID_FK" FOREIGN KEY ("NAME_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGENAME" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGE" ADD CONSTRAINT "RHN_PACKAGE_EID_FK" FOREIGN KEY ("EVR_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEEVR" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGE" ADD CONSTRAINT "RHN_PACKAGE_PAID_FK" FOREIGN KEY ("PACKAGE_ARCH_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEARCH" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGE" ADD CONSTRAINT "RHN_PACKAGE_GROUP_FK" FOREIGN KEY ("PACKAGE_GROUP")
	  REFERENCES "SPACEUSER"."RHNPACKAGEGROUP" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGE" ADD CONSTRAINT "RHN_PACKAGE_SRCRPMID_FK" FOREIGN KEY ("SOURCE_RPM_ID")
	  REFERENCES "SPACEUSER"."RHNSOURCERPM" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGE" ADD CONSTRAINT "RHN_PACKAGE_CHSUM_FK" FOREIGN KEY ("CHECKSUM_ID")
	  REFERENCES "SPACEUSER"."RHNCHECKSUM" ("ID") ENABLE;
