-- created by Oraschemadoc Wed Jan  9 15:07:01 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNPACKAGECHANGELOGREC"
   (	"ID" NUMBER NOT NULL ENABLE,
	"PACKAGE_ID" NUMBER NOT NULL ENABLE,
	"CHANGELOG_DATA_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNPACKAGECHANGELOGREC" ADD CONSTRAINT "RHN_PKG_CLR_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGECHANGELOGREC" ADD CONSTRAINT "RHN_PKG_CLR_PID_FK" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGECHANGELOGREC" ADD CONSTRAINT "RHN_PKG_CLR_CLD_FK" FOREIGN KEY ("CHANGELOG_DATA_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGECHANGELOGDATA" ("ID") ENABLE;
