-- created by Oraschemadoc Wed Jan  9 15:07:02 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNPACKAGEREPODATA"
   (	"PACKAGE_ID" NUMBER NOT NULL ENABLE,
	"PRIMARY_XML" BLOB,
	"FILELIST" BLOB,
	"OTHER" BLOB,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ;
  ALTER TABLE "SPACEUSER"."RHNPACKAGEREPODATA" ADD CONSTRAINT "RHNPACKAGEREPODATA_PK" PRIMARY KEY ("PACKAGE_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNPACKAGEREPODATA" ADD CONSTRAINT "RHN_PKEY_RD_PID_FK" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGE" ("ID") ON DELETE CASCADE ENABLE;
