-- created by Oraschemadoc Wed Jan  9 15:07:03 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNRELEASECHANNELMAP"
   (	"PRODUCT" VARCHAR2(64) NOT NULL ENABLE,
	"VERSION" VARCHAR2(64) NOT NULL ENABLE,
	"RELEASE" VARCHAR2(64) NOT NULL ENABLE,
	"CHANNEL_ARCH_ID" NUMBER NOT NULL ENABLE,
	"CHANNEL_ID" NUMBER NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNRELEASECHANNELMAP" ADD CONSTRAINT "RHN_RCM_PVA_DEF_UNIQ" UNIQUE ("PRODUCT", "VERSION", "CHANNEL_ARCH_ID", "RELEASE") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNRELEASECHANNELMAP" ADD CONSTRAINT "RHN_RCM_CAID_FK" FOREIGN KEY ("CHANNEL_ARCH_ID")
	  REFERENCES "SPACEUSER"."RHNCHANNELARCH" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNRELEASECHANNELMAP" ADD CONSTRAINT "RHN_RCM_CID_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "SPACEUSER"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE;
