-- created by Oraschemadoc Wed Jan  9 15:07:03 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNREGTOKENENTITLEMENT"
   (	"REG_TOKEN_ID" NUMBER NOT NULL ENABLE,
	"SERVER_GROUP_TYPE_ID" NUMBER NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNREGTOKENENTITLEMENT" ADD CONSTRAINT "RHN_REG_TOK_ENT_RTID_FK" FOREIGN KEY ("REG_TOKEN_ID")
	  REFERENCES "SPACEUSER"."RHNREGTOKEN" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNREGTOKENENTITLEMENT" ADD CONSTRAINT "RHN_REG_TOK_ENT_SGTID_FK" FOREIGN KEY ("SERVER_GROUP_TYPE_ID")
	  REFERENCES "SPACEUSER"."RHNSERVERGROUPTYPE" ("ID") ON DELETE CASCADE ENABLE;
