-- created by Oraschemadoc Wed Jan  9 15:07:03 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNREGTOKENPACKAGES"
   (	"ID" NUMBER NOT NULL ENABLE,
	"TOKEN_ID" NUMBER NOT NULL ENABLE,
	"NAME_ID" NUMBER NOT NULL ENABLE,
	"ARCH_ID" NUMBER
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNREGTOKENPACKAGES" ADD CONSTRAINT "RHN_REG_TOK_PKG_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNREGTOKENPACKAGES" ADD CONSTRAINT "RHN_REG_TOK_PKG_ID_FK" FOREIGN KEY ("TOKEN_ID")
	  REFERENCES "SPACEUSER"."RHNREGTOKEN" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNREGTOKENPACKAGES" ADD CONSTRAINT "RHN_REG_TOK_PKG_SGS_FK" FOREIGN KEY ("NAME_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGENAME" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNREGTOKENPACKAGES" ADD CONSTRAINT "RHN_REG_TOK_PKG_AID_FK" FOREIGN KEY ("ARCH_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEARCH" ("ID") ON DELETE CASCADE ENABLE;
