-- created by Oraschemadoc Wed Jan  9 15:07:03 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNREGTOKENORGDEFAULT"
   (	"ORG_ID" NUMBER NOT NULL ENABLE,
	"REG_TOKEN_ID" NUMBER
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNREGTOKENORGDEFAULT" ADD CONSTRAINT "RHN_REG_TOKEN_DEF_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNREGTOKENORGDEFAULT" ADD CONSTRAINT "RHN_REG_TOKEN_DEF_TOKID_FK" FOREIGN KEY ("REG_TOKEN_ID")
	  REFERENCES "SPACEUSER"."RHNREGTOKEN" ("ID") ON DELETE CASCADE ENABLE;
