-- created by Oraschemadoc Wed Jan  9 15:07:04 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVERDMI"
   (	"ID" NUMBER NOT NULL ENABLE,
	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"VENDOR" VARCHAR2(256),
	"SYSTEM" VARCHAR2(256),
	"PRODUCT" VARCHAR2(256),
	"BIOS_VENDOR" VARCHAR2(256),
	"BIOS_VERSION" VARCHAR2(256),
	"BIOS_RELEASE" VARCHAR2(256),
	"ASSET" VARCHAR2(256),
	"BOARD" VARCHAR2(256),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSERVERDMI" ADD CONSTRAINT "RHN_SERVER_DMI_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERDMI" ADD CONSTRAINT "RHN_SERVER_DMI_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ENABLE;
