-- created by Oraschemadoc Wed Jan  9 15:07:05 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVERNEEDEDCACHE"
   (	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"ERRATA_ID" NUMBER,
	"PACKAGE_ID" NUMBER NOT NULL ENABLE,
	"CHANNEL_ID" NUMBER
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSERVERNEEDEDCACHE" ADD CONSTRAINT "RHN_SNCP_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERNEEDEDCACHE" ADD CONSTRAINT "RHN_SNCP_EID_FK" FOREIGN KEY ("ERRATA_ID")
	  REFERENCES "SPACEUSER"."RHNERRATA" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERNEEDEDCACHE" ADD CONSTRAINT "RHN_SNCP_PID_FK" FOREIGN KEY ("PACKAGE_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERNEEDEDCACHE" ADD CONSTRAINT "RHN_SNCP_CID_FK" FOREIGN KEY ("CHANNEL_ID")
	  REFERENCES "SPACEUSER"."RHNCHANNEL" ("ID") ON DELETE CASCADE ENABLE;
