-- created by Oraschemadoc Wed Jan  9 15:07:06 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVER_LOG"
   (	"ID" NUMBER NOT NULL ENABLE,
	"LOG_ID" NUMBER NOT NULL ENABLE,
	"ACTION" CHAR(1) NOT NULL ENABLE,
	"ORG_ID" NUMBER NOT NULL ENABLE,
	"DIGITAL_SERVER_ID" VARCHAR2(64) NOT NULL ENABLE,
	"SERVER_ARCH_ID" NUMBER NOT NULL ENABLE,
	"OS" VARCHAR2(64) NOT NULL ENABLE,
	"RELEASE" VARCHAR2(64) NOT NULL ENABLE,
	"NAME" VARCHAR2(128),
	"DESCRIPTION" VARCHAR2(256),
	"INFO" VARCHAR2(128),
	"SECRET" VARCHAR2(64) NOT NULL ENABLE,
	"CREATOR_ID" NUMBER,
	"AUTO_UPDATE" CHAR(1) NOT NULL ENABLE,
	"RUNNING_KERNEL" VARCHAR2(64),
	"LAST_BOOT" NUMBER NOT NULL ENABLE,
	"PROVISION_STATE_ID" NUMBER,
	"CHANNELS_CHANGED" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"COBBLER_ID" VARCHAR2(64)
   ) ;
  ALTER TABLE "SPACEUSER"."RHNSERVER_LOG" ADD FOREIGN KEY ("LOG_ID")
	  REFERENCES "SPACEUSER"."LOG" ("ID") ENABLE;
