-- created by Oraschemadoc Wed Jan  9 15:07:05 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVERNETADDRESS4"
   (	"INTERFACE_ID" NUMBER NOT NULL ENABLE,
	"ADDRESS" VARCHAR2(64),
	"NETMASK" VARCHAR2(64),
	"BROADCAST" VARCHAR2(64),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSERVERNETADDRESS4" ADD CONSTRAINT "RHN_SRV_NET_ADDR4_IID_ADDR_UQ" UNIQUE ("INTERFACE_ID", "ADDRESS") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERNETADDRESS4" ADD CONSTRAINT "RHN_SRV_NET_IADDRESS4_IID_FK" FOREIGN KEY ("INTERFACE_ID")
	  REFERENCES "SPACEUSER"."RHNSERVERNETINTERFACE" ("ID") ON DELETE CASCADE ENABLE;
