-- created by Oraschemadoc Wed Jan  9 15:07:06 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVERSERVERGROUPARCHCOMPAT"
   (	"SERVER_ARCH_ID" NUMBER NOT NULL ENABLE,
	"SERVER_GROUP_TYPE" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSERVERSERVERGROUPARCHCOMPAT" ADD CONSTRAINT "RHN_SSG_AC_SAID_FK" FOREIGN KEY ("SERVER_ARCH_ID")
	  REFERENCES "SPACEUSER"."RHNSERVERARCH" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERSERVERGROUPARCHCOMPAT" ADD CONSTRAINT "RHN_SSG_AC_SGT_FK" FOREIGN KEY ("SERVER_GROUP_TYPE")
	  REFERENCES "SPACEUSER"."RHNSERVERGROUPTYPE" ("ID") ENABLE;
