-- created by Oraschemadoc Wed Jan  9 15:07:04 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVERCRASHFILE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"CRASH_ID" NUMBER NOT NULL ENABLE,
	"FILENAME" VARCHAR2(512) NOT NULL ENABLE,
	"PATH" VARCHAR2(1024) NOT NULL ENABLE,
	"FILESIZE" NUMBER NOT NULL ENABLE,
	"IS_UPLOADED" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSERVERCRASHFILE" ADD CONSTRAINT "RHN_SERVER_CRASH_FILE_UPL_CK" CHECK (is_uploaded in ('Y', 'N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERCRASHFILE" ADD CONSTRAINT "RHN_SERVER_CRASH_FILE_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERCRASHFILE" ADD CONSTRAINT "RHN_SERVER_CRASH_FILE_CIS_FK" FOREIGN KEY ("CRASH_ID")
	  REFERENCES "SPACEUSER"."RHNSERVERCRASH" ("ID") ON DELETE CASCADE ENABLE;
