-- created by Oraschemadoc Wed Jan  9 15:07:03 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSATELLITEINFO"
   (	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"EVR_ID" NUMBER,
	"CERT" BLOB NOT NULL ENABLE,
	"PRODUCT" VARCHAR2(256) NOT NULL ENABLE,
	"OWNER" VARCHAR2(256) NOT NULL ENABLE,
	"ISSUED_STRING" VARCHAR2(256),
	"EXPIRATION_STRING" VARCHAR2(256),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSATELLITEINFO" ADD CONSTRAINT "RHN_SATELLITE_INFO_SID_UQ" UNIQUE ("SERVER_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSATELLITEINFO" ADD CONSTRAINT "RHN_SATELLITE_INFO_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSATELLITEINFO" ADD CONSTRAINT "RHN_SATELLITE_INFO_EID_FK" FOREIGN KEY ("EVR_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEEVR" ("ID") ENABLE;
