-- created by Oraschemadoc Wed Jan  9 15:07:06 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSET"
   (	"USER_ID" NUMBER NOT NULL ENABLE,
	"LABEL" VARCHAR2(32) NOT NULL ENABLE,
	"ELEMENT" NUMBER NOT NULL ENABLE,
	"ELEMENT_TWO" NUMBER,
	"ELEMENT_THREE" NUMBER
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSET" ADD CONSTRAINT "RHN_SET_USER_LABEL_ELEM_UNQ" UNIQUE ("USER_ID", "LABEL", "ELEMENT", "ELEMENT_TWO", "ELEMENT_THREE") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSET" ADD CONSTRAINT "RHN_SET_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE;
