-- created by Oraschemadoc Wed Jan  9 15:07:06 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSNAPSHOTPACKAGE"
   (	"SNAPSHOT_ID" NUMBER NOT NULL ENABLE,
	"NEVRA_ID" NUMBER NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSNAPSHOTPACKAGE" ADD CONSTRAINT "RHN_SNAPSHOTPKG_SID_FK" FOREIGN KEY ("SNAPSHOT_ID")
	  REFERENCES "SPACEUSER"."RHNSNAPSHOT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSNAPSHOTPACKAGE" ADD CONSTRAINT "RHN_SNAPSHOTPKG_NID_FK" FOREIGN KEY ("NEVRA_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGENEVRA" ("ID") ENABLE;
