-- created by Oraschemadoc Wed Jan  9 15:07:05 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVERINFO"
   (	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"CHECKIN" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp),
	"CHECKIN_COUNTER" NUMBER DEFAULT (0)
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSERVERINFO" ADD CONSTRAINT "RHN_SERVER_INFO_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ENABLE;
