-- created by Oraschemadoc Wed Jan  9 15:07:05 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVERPROFILE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ORG_ID" NUMBER NOT NULL ENABLE,
	"BASE_CHANNEL" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(128),
	"DESCRIPTION" VARCHAR2(256),
	"INFO" VARCHAR2(128),
	"PROFILE_TYPE_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSERVERPROFILE" ADD CONSTRAINT "RHN_SERVER_PROFILE_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERPROFILE" ADD CONSTRAINT "RHN_SERVER_PROFILE_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERPROFILE" ADD CONSTRAINT "RHN_SERVER_PROFILE_BCID_FK" FOREIGN KEY ("BASE_CHANNEL")
	  REFERENCES "SPACEUSER"."RHNCHANNEL" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERPROFILE" ADD CONSTRAINT "RHN_SERVER_PROFILE_PTYPE_FK" FOREIGN KEY ("PROFILE_TYPE_ID")
	  REFERENCES "SPACEUSER"."RHNSERVERPROFILETYPE" ("ID") ENABLE;
