-- created by Oraschemadoc Wed Jan  9 15:07:05 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVERPATH"
   (	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"PROXY_SERVER_ID" NUMBER NOT NULL ENABLE,
	"POSITION" NUMBER NOT NULL ENABLE,
	"HOSTNAME" VARCHAR2(256) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSERVERPATH" ADD CONSTRAINT "RHN_SERVERPATH_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERPATH" ADD CONSTRAINT "RHN_SERVERPATH_PSID_FK" FOREIGN KEY ("PROXY_SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ENABLE;
