-- created by Oraschemadoc Wed Jan  9 15:07:04 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVERGROUPTYPEFEATURE"
   (	"SERVER_GROUP_TYPE_ID" NUMBER NOT NULL ENABLE,
	"FEATURE_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSERVERGROUPTYPEFEATURE" ADD CONSTRAINT "RHN_SGT_SGID_FK" FOREIGN KEY ("SERVER_GROUP_TYPE_ID")
	  REFERENCES "SPACEUSER"."RHNSERVERGROUPTYPE" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERGROUPTYPEFEATURE" ADD CONSTRAINT "RHN_SGT_FID_FK" FOREIGN KEY ("FEATURE_ID")
	  REFERENCES "SPACEUSER"."RHNFEATURE" ("ID") ENABLE;
