-- created by Oraschemadoc Wed Jan  9 15:07:07 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSOURCERPM"
   (	"ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(256) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSOURCERPM" ADD CONSTRAINT "RHN_SOURCERPM_ID_PK" PRIMARY KEY ("ID") ENABLE;
