-- created by Oraschemadoc Wed Jan  9 15:07:07 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSSMOPERATIONSERVER"
   (	"OPERATION_ID" NUMBER,
	"SERVER_ID" NUMBER,
	"NOTE" VARCHAR2(256) DEFAULT NULL
   ) ;
  ALTER TABLE "SPACEUSER"."RHNSSMOPERATIONSERVER" ADD CONSTRAINT "RHN_SSMOPS_SSMOP_FK" FOREIGN KEY ("OPERATION_ID")
	  REFERENCES "SPACEUSER"."RHNSSMOPERATION" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSSMOPERATIONSERVER" ADD CONSTRAINT "RHN_SSMOPS_SER_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ON DELETE CASCADE ENABLE;
