-- created by Oraschemadoc Wed Jan  9 15:07:04 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVERGROUPTYPE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"LABEL" VARCHAR2(32) NOT NULL ENABLE,
	"NAME" VARCHAR2(64) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"PERMANENT" CHAR(1) DEFAULT ('Y') NOT NULL ENABLE,
	"IS_BASE" CHAR(1) DEFAULT ('Y') NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSERVERGROUPTYPE" ADD CONSTRAINT "RHN_SERVERGROUPTYPE_PERM_CK" CHECK (permanent in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERGROUPTYPE" ADD CONSTRAINT "RHN_SERVERGROUPTYPE_ISBASE_CK" CHECK (is_base in ('Y','N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERGROUPTYPE" ADD CONSTRAINT "RHN_SERVERGROUPTYPE_ID_PK" PRIMARY KEY ("ID") ENABLE;
