-- created by Oraschemadoc Wed Jan  9 15:07:07 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSSMOPERATION"
   (	"ID" NUMBER NOT NULL ENABLE,
	"USER_ID" NUMBER NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(256) NOT NULL ENABLE,
	"STATUS" VARCHAR2(32) NOT NULL ENABLE,
	"STARTED" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ;
  ALTER TABLE "SPACEUSER"."RHNSSMOPERATION" ADD CONSTRAINT "RHN_SSMOP_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSSMOPERATION" ADD CONSTRAINT "RHN_SSMOP_USER_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE;
