-- created by Oraschemadoc Wed Jan  9 15:07:03 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVERACTIONPACKAGERESULT"
   (	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"ACTION_PACKAGE_ID" NUMBER NOT NULL ENABLE,
	"RESULT_CODE" NUMBER NOT NULL ENABLE,
	"STDOUT" BLOB,
	"STDERR" BLOB,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSERVERACTIONPACKAGERESULT" ADD CONSTRAINT "RHN_SAP_RESULT_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERACTIONPACKAGERESULT" ADD CONSTRAINT "RHN_SAP_RESULT_APID_FK" FOREIGN KEY ("ACTION_PACKAGE_ID")
	  REFERENCES "SPACEUSER"."RHNACTIONPACKAGE" ("ID") ON DELETE CASCADE ENABLE;
