-- created by Oraschemadoc Wed Jan  9 15:07:05 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVERGROUP_LOG"
   (	"ID" NUMBER NOT NULL ENABLE,
	"LOG_ID" NUMBER NOT NULL ENABLE,
	"ACTION" CHAR(1) NOT NULL ENABLE,
	"NAME" VARCHAR2(64) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(1024) NOT NULL ENABLE,
	"CURRENT_MEMBERS" NUMBER NOT NULL ENABLE,
	"GROUP_TYPE" NUMBER,
	"ORG_ID" NUMBER NOT NULL ENABLE
   ) ;
  ALTER TABLE "SPACEUSER"."RHNSERVERGROUP_LOG" ADD FOREIGN KEY ("LOG_ID")
	  REFERENCES "SPACEUSER"."LOG" ("ID") ENABLE;
