-- created by Oraschemadoc Wed Jan  9 15:07:06 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSNAPSHOTTAG"
   (	"SNAPSHOT_ID" NUMBER NOT NULL ENABLE,
	"TAG_ID" NUMBER NOT NULL ENABLE,
	"SERVER_ID" NUMBER,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSNAPSHOTTAG" ADD CONSTRAINT "RHN_ST_SSID_FK" FOREIGN KEY ("SNAPSHOT_ID")
	  REFERENCES "SPACEUSER"."RHNSNAPSHOT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSNAPSHOTTAG" ADD CONSTRAINT "RHN_ST_TID_FK" FOREIGN KEY ("TAG_ID")
	  REFERENCES "SPACEUSER"."RHNTAG" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSNAPSHOTTAG" ADD CONSTRAINT "RHN_ST_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ENABLE;
