-- created by Oraschemadoc Wed Jan  9 15:07:05 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVERNOTES"
   (	"ID" NUMBER NOT NULL ENABLE,
	"CREATOR" NUMBER,
	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"SUBJECT" VARCHAR2(80) NOT NULL ENABLE,
	"NOTE" VARCHAR2(4000),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSERVERNOTES" ADD CONSTRAINT "RHN_SERVERNOTES_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERNOTES" ADD CONSTRAINT "RHN_SERVERNOTES_CREATOR_FK" FOREIGN KEY ("CREATOR")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERNOTES" ADD CONSTRAINT "RHN_SERVERNOTES_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ENABLE;
