-- created by Oraschemadoc Wed Jan  9 15:07:04 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVERACTIONSCRIPTRESULT"
   (	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"ACTION_SCRIPT_ID" NUMBER NOT NULL ENABLE,
	"OUTPUT" BLOB,
	"START_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE,
	"STOP_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE,
	"RETURN_CODE" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSERVERACTIONSCRIPTRESULT" ADD CONSTRAINT "RHN_SERVERAS_RESULT_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVERACTIONSCRIPTRESULT" ADD CONSTRAINT "RHN_SERVERAS_RESULT_ASID_FK" FOREIGN KEY ("ACTION_SCRIPT_ID")
	  REFERENCES "SPACEUSER"."RHNACTIONSCRIPT" ("ID") ON DELETE CASCADE ENABLE;
