-- created by Oraschemadoc Wed Jan  9 15:07:03 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSERVER"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ORG_ID" NUMBER NOT NULL ENABLE,
	"DIGITAL_SERVER_ID" VARCHAR2(64) NOT NULL ENABLE,
	"SERVER_ARCH_ID" NUMBER NOT NULL ENABLE,
	"OS" VARCHAR2(64) NOT NULL ENABLE,
	"RELEASE" VARCHAR2(64) NOT NULL ENABLE,
	"NAME" VARCHAR2(128),
	"DESCRIPTION" VARCHAR2(256),
	"INFO" VARCHAR2(128),
	"SECRET" VARCHAR2(64) NOT NULL ENABLE,
	"CREATOR_ID" NUMBER,
	"AUTO_UPDATE" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"RUNNING_KERNEL" VARCHAR2(64),
	"LAST_BOOT" NUMBER DEFAULT (0) NOT NULL ENABLE,
	"PROVISION_STATE_ID" NUMBER,
	"CHANNELS_CHANGED" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"COBBLER_ID" VARCHAR2(64),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSERVER" ADD CONSTRAINT "RHN_SERVER_UPDATE_CK" CHECK (auto_update in ('Y', 'N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVER" ADD CONSTRAINT "RHN_SERVER_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVER" ADD CONSTRAINT "RHN_SERVER_OID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVER" ADD CONSTRAINT "RHN_SERVER_SAID_FK" FOREIGN KEY ("SERVER_ARCH_ID")
	  REFERENCES "SPACEUSER"."RHNSERVERARCH" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVER" ADD CONSTRAINT "RHN_SERVER_CREATOR_FK" FOREIGN KEY ("CREATOR_ID")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSERVER" ADD CONSTRAINT "RHN_SERVER_PSID_FK" FOREIGN KEY ("PROVISION_STATE_ID")
	  REFERENCES "SPACEUSER"."RHNPROVISIONSTATE" ("ID") ENABLE;
