-- created by Oraschemadoc Wed Jan  9 15:07:07 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNSYSTEMMIGRATIONS"
   (	"ORG_ID_TO" NUMBER,
	"ORG_ID_FROM" NUMBER,
	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"MIGRATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNSYSTEMMIGRATIONS" ADD CONSTRAINT "RHN_SYS_MIG_OIDTO_FK" FOREIGN KEY ("ORG_ID_TO")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSYSTEMMIGRATIONS" ADD CONSTRAINT "RHN_SYS_MIG_OIDFRM_FK" FOREIGN KEY ("ORG_ID_FROM")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "SPACEUSER"."RHNSYSTEMMIGRATIONS" ADD CONSTRAINT "RHN_SYS_MIG_SID_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ON DELETE CASCADE ENABLE;
