-- created by Oraschemadoc Wed Jan  9 15:07:07 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNTRANSACTIONPACKAGE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"OPERATION" NUMBER NOT NULL ENABLE,
	"NAME_ID" NUMBER NOT NULL ENABLE,
	"EVR_ID" NUMBER NOT NULL ENABLE,
	"PACKAGE_ARCH_ID" NUMBER
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNTRANSACTIONPACKAGE" ADD CONSTRAINT "RHN_TRANSPACK_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNTRANSACTIONPACKAGE" ADD CONSTRAINT "RHN_TRANSPACK_OP_FK" FOREIGN KEY ("OPERATION")
	  REFERENCES "SPACEUSER"."RHNTRANSACTIONOPERATION" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNTRANSACTIONPACKAGE" ADD CONSTRAINT "RHN_TRANSPACK_NID_FK" FOREIGN KEY ("NAME_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGENAME" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNTRANSACTIONPACKAGE" ADD CONSTRAINT "RHN_TRANSPACK_EID_FK" FOREIGN KEY ("EVR_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEEVR" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNTRANSACTIONPACKAGE" ADD CONSTRAINT "RHN_TRANSPACK_PAID_FK" FOREIGN KEY ("PACKAGE_ARCH_ID")
	  REFERENCES "SPACEUSER"."RHNPACKAGEARCH" ("ID") ENABLE;
