-- created by Oraschemadoc Wed Jan  9 15:07:07 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNTIMEZONE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"OLSON_NAME" VARCHAR2(128) NOT NULL ENABLE,
	"DISPLAY_NAME" VARCHAR2(128) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNTIMEZONE" ADD CONSTRAINT "RHN_TIMEZONE_ID_PK" PRIMARY KEY ("ID") ENABLE;
