-- created by Oraschemadoc Wed Jan  9 15:07:07 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNTASKORUN"
   (	"ID" NUMBER NOT NULL ENABLE,
	"TEMPLATE_ID" NUMBER NOT NULL ENABLE,
	"SCHEDULE_ID" NUMBER NOT NULL ENABLE,
	"ORG_ID" NUMBER,
	"START_TIME" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"END_TIME" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"STD_OUTPUT_PATH" VARCHAR2(100),
	"STD_ERROR_PATH" VARCHAR2(100),
	"STATUS" VARCHAR2(12),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ;
  ALTER TABLE "SPACEUSER"."RHNTASKORUN" ADD CONSTRAINT "RHN_TASKO_RUN_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNTASKORUN" ADD CONSTRAINT "RHN_TASKO_RUN_TEMPLATE_FK" FOREIGN KEY ("TEMPLATE_ID")
	  REFERENCES "SPACEUSER"."RHNTASKOTEMPLATE" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNTASKORUN" ADD CONSTRAINT "RHN_TASKO_RUN_SCHEDULE_FK" FOREIGN KEY ("SCHEDULE_ID")
	  REFERENCES "SPACEUSER"."RHNTASKOSCHEDULE" ("ID") ON DELETE CASCADE ENABLE;
