-- created by Oraschemadoc Wed Jan  9 15:07:07 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNTASKOSCHEDULE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"JOB_LABEL" VARCHAR2(50) NOT NULL ENABLE,
	"BUNCH_ID" NUMBER NOT NULL ENABLE,
	"ORG_ID" NUMBER,
	"ACTIVE_FROM" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"ACTIVE_TILL" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"CRON_EXPR" VARCHAR2(120),
	"DATA" BLOB,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ;
  ALTER TABLE "SPACEUSER"."RHNTASKOSCHEDULE" ADD CONSTRAINT "RHN_TASKO_SCHEDULE_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNTASKOSCHEDULE" ADD CONSTRAINT "RHN_TASKO_SCHEDULE_BUNCH_FK" FOREIGN KEY ("BUNCH_ID")
	  REFERENCES "SPACEUSER"."RHNTASKOBUNCH" ("ID") ENABLE;
