-- created by Oraschemadoc Wed Jan  9 15:07:07 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNTASKOTEMPLATE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"BUNCH_ID" NUMBER NOT NULL ENABLE,
	"TASK_ID" NUMBER NOT NULL ENABLE,
	"ORDERING" NUMBER NOT NULL ENABLE,
	"START_IF" VARCHAR2(10),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ;
  ALTER TABLE "SPACEUSER"."RHNTASKOTEMPLATE" ADD CONSTRAINT "RHN_TASKO_TEMPLATE_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNTASKOTEMPLATE" ADD CONSTRAINT "TASKO_TEMPLATE_ORDERING_UQ" UNIQUE ("BUNCH_ID", "ORDERING") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNTASKOTEMPLATE" ADD CONSTRAINT "RHN_TASKO_TEMPLATE_BUNCH_FK" FOREIGN KEY ("BUNCH_ID")
	  REFERENCES "SPACEUSER"."RHNTASKOBUNCH" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNTASKOTEMPLATE" ADD CONSTRAINT "RHN_TASKO_TEMPLATE_TASK_FK" FOREIGN KEY ("TASK_ID")
	  REFERENCES "SPACEUSER"."RHNTASKOTASK" ("ID") ENABLE;
