-- created by Oraschemadoc Wed Jan  9 15:07:07 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNTEMPLATESTRING"
   (	"ID" NUMBER NOT NULL ENABLE,
	"CATEGORY_ID" NUMBER NOT NULL ENABLE,
	"LABEL" VARCHAR2(64) NOT NULL ENABLE,
	"VALUE" VARCHAR2(4000),
	"DESCRIPTION" VARCHAR2(512) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNTEMPLATESTRING" ADD CONSTRAINT "RHN_TEMPLATE_STR_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNTEMPLATESTRING" ADD CONSTRAINT "RHN_TEMPLATE_STR_CID_LABEL_UQ" UNIQUE ("CATEGORY_ID", "LABEL") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNTEMPLATESTRING" ADD CONSTRAINT "RHN_TEMPLATE_STR_CID_FK" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "SPACEUSER"."RHNTEMPLATECATEGORY" ("ID") ENABLE;
