-- created by Oraschemadoc Wed Jan  9 15:07:07 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNTASKQUEUE"
   (	"ORG_ID" NUMBER NOT NULL ENABLE,
	"TASK_NAME" VARCHAR2(64) NOT NULL ENABLE,
	"TASK_DATA" NUMBER,
	"PRIORITY" NUMBER DEFAULT (0),
	"EARLIEST" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNTASKQUEUE" ADD CONSTRAINT "RHN_TASK_QUEUE_ORG_ID_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ON DELETE CASCADE ENABLE;
