-- created by Oraschemadoc Wed Jan  9 15:07:07 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNTINYURL"
   (	"TOKEN" VARCHAR2(64) NOT NULL ENABLE,
	"URL" VARCHAR2(512) NOT NULL ENABLE,
	"ENABLED" VARCHAR2(1) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"EXPIRES" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNTINYURL" ADD CONSTRAINT "RHN_TU_ENABLED_CK" CHECK (enabled in ('Y','N')) ENABLE;
