-- created by Oraschemadoc Wed Jan  9 15:07:07 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNTASKOBUNCH"
   (	"ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(80) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(200),
	"ORG_BUNCH" VARCHAR2(1),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ;
  ALTER TABLE "SPACEUSER"."RHNTASKOBUNCH" ADD CONSTRAINT "RHN_TASKO_BUNCH_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNTASKOBUNCH" ADD CONSTRAINT "TASKO_BUNCH_NAME_UQ" UNIQUE ("NAME") ENABLE;
