-- created by Oraschemadoc Wed Jan  9 15:07:07 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNTASKOTASK"
   (	"ID" NUMBER NOT NULL ENABLE,
	"NAME" VARCHAR2(80) NOT NULL ENABLE,
	"CLASS" VARCHAR2(60) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ;
  ALTER TABLE "SPACEUSER"."RHNTASKOTASK" ADD CONSTRAINT "RHN_TASKO_TASK_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNTASKOTASK" ADD CONSTRAINT "RHN_TASKO_TASK_NAME_UQ" UNIQUE ("NAME") ENABLE;
