-- created by Oraschemadoc Wed Jan  9 15:07:08 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNUSERDEFAULTSYSTEMGROUPS"
   (	"USER_ID" NUMBER NOT NULL ENABLE,
	"SYSTEM_GROUP_ID" NUMBER NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNUSERDEFAULTSYSTEMGROUPS" ADD CONSTRAINT "RHN_UDSG_UID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNUSERDEFAULTSYSTEMGROUPS" ADD CONSTRAINT "RHN_UDSG_CIDFFK" FOREIGN KEY ("SYSTEM_GROUP_ID")
	  REFERENCES "SPACEUSER"."RHNSERVERGROUP" ("ID") ON DELETE CASCADE ENABLE;
