-- created by Oraschemadoc Wed Jan  9 15:07:08 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNUSERGROUPMEMBERS"
   (	"USER_ID" NUMBER NOT NULL ENABLE,
	"USER_GROUP_ID" NUMBER NOT NULL ENABLE,
	"TEMPORARY" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNUSERGROUPMEMBERS" ADD CONSTRAINT "RHN_UGMEMBERS_T_CK" CHECK (temporary in ('Y', 'N')) ENABLE;
  ALTER TABLE "SPACEUSER"."RHNUSERGROUPMEMBERS" ADD CONSTRAINT "RHN_UGMEMBERS_UID_FK" FOREIGN KEY ("USER_ID")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNUSERGROUPMEMBERS" ADD CONSTRAINT "RHN_UGMEMBERS_UGID_FK" FOREIGN KEY ("USER_GROUP_ID")
	  REFERENCES "SPACEUSER"."RHNUSERGROUP" ("ID") ENABLE;
