-- created by Oraschemadoc Wed Jan  9 15:07:08 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNUSEREXTGROUPMAPPING"
   (	"ID" NUMBER NOT NULL ENABLE,
	"EXT_GROUP_ID" NUMBER NOT NULL ENABLE,
	"INT_GROUP_TYPE_ID" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNUSEREXTGROUPMAPPING" ADD CONSTRAINT "RHN_USEREXTGROUPMAP_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNUSEREXTGROUPMAPPING" ADD CONSTRAINT "RHN_USEREXTGROUPMAP_E_FK" FOREIGN KEY ("EXT_GROUP_ID")
	  REFERENCES "SPACEUSER"."RHNUSEREXTGROUP" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNUSEREXTGROUPMAPPING" ADD CONSTRAINT "RHN_USEREXTGROUPMAP_I_FK" FOREIGN KEY ("INT_GROUP_TYPE_ID")
	  REFERENCES "SPACEUSER"."RHNUSERGROUPTYPE" ("ID") ON DELETE CASCADE ENABLE;
