-- created by Oraschemadoc Wed Jan  9 15:07:09 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNVISIBLEOBJECTS"
   (	"PXT_SESSION_ID" NUMBER NOT NULL ENABLE,
	"OBJECT_ID" NUMBER NOT NULL ENABLE,
	"OBJECT_TYPE" VARCHAR2(40) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNVISIBLEOBJECTS" ADD CONSTRAINT "RHN_VIS_OBJS_SESS_FK" FOREIGN KEY ("PXT_SESSION_ID")
	  REFERENCES "SPACEUSER"."PXTSESSIONS" ("ID") ON DELETE CASCADE ENABLE;
