-- created by Oraschemadoc Wed Jan  9 15:07:08 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNVIRTUALINSTANCEINFO"
   (	"NAME" VARCHAR2(128),
	"INSTANCE_ID" NUMBER NOT NULL ENABLE,
	"INSTANCE_TYPE" NUMBER NOT NULL ENABLE,
	"MEMORY_SIZE_K" NUMBER,
	"VCPUS" NUMBER,
	"STATE" NUMBER NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNVIRTUALINSTANCEINFO" ADD CONSTRAINT "RHN_VII_VIID_FK" FOREIGN KEY ("INSTANCE_ID")
	  REFERENCES "SPACEUSER"."RHNVIRTUALINSTANCE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNVIRTUALINSTANCEINFO" ADD CONSTRAINT "RHN_VII_IT_FK" FOREIGN KEY ("INSTANCE_TYPE")
	  REFERENCES "SPACEUSER"."RHNVIRTUALINSTANCETYPE" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNVIRTUALINSTANCEINFO" ADD CONSTRAINT "RHN_VII_STATE_FK" FOREIGN KEY ("STATE")
	  REFERENCES "SPACEUSER"."RHNVIRTUALINSTANCESTATE" ("ID") ENABLE;
