-- created by Oraschemadoc Wed Jan  9 15:07:08 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNVIRTUALINSTANCE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"HOST_SYSTEM_ID" NUMBER,
	"VIRTUAL_SYSTEM_ID" NUMBER,
	"UUID" VARCHAR2(128),
	"CONFIRMED" NUMBER(1,0) DEFAULT (1) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNVIRTUALINSTANCE" ADD CONSTRAINT "RHN_VI_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNVIRTUALINSTANCE" ADD CONSTRAINT "RHN_VI_HSI_FK" FOREIGN KEY ("HOST_SYSTEM_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNVIRTUALINSTANCE" ADD CONSTRAINT "RHN_VI_VSI_FK" FOREIGN KEY ("VIRTUAL_SYSTEM_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ENABLE;
