-- created by Oraschemadoc Wed Jan  9 15:07:08 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNVIRTUALINSTANCEEVENTLOG"
   (	"ID" NUMBER NOT NULL ENABLE,
	"VIRTUAL_INSTANCE_ID" NUMBER,
	"EVENT_TYPE" NUMBER NOT NULL ENABLE,
	"EVENT_METADATA" VARCHAR2(4000),
	"OLD_STATE" NUMBER NOT NULL ENABLE,
	"NEW_STATE" NUMBER NOT NULL ENABLE,
	"OLD_MEMORY_SIZE_K" NUMBER,
	"NEW_MEMORY_SIZE_K" NUMBER,
	"OLD_VCPUS" NUMBER,
	"NEW_VCPUS" NUMBER,
	"OLD_HOST_SYSTEM_ID" NUMBER,
	"NEW_HOST_SYSTEM_ID" NUMBER,
	"OLD_HOST_SYSTEM_NAME" VARCHAR2(128),
	"NEW_HOST_SYSTEM_NAME" VARCHAR2(128),
	"LOCAL_TIMESTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNVIRTUALINSTANCEEVENTLOG" ADD CONSTRAINT "RHN_VIEL_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNVIRTUALINSTANCEEVENTLOG" ADD CONSTRAINT "RHN_VIEL_VII_FK" FOREIGN KEY ("VIRTUAL_INSTANCE_ID")
	  REFERENCES "SPACEUSER"."RHNVIRTUALINSTANCE" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNVIRTUALINSTANCEEVENTLOG" ADD CONSTRAINT "RHN_VIEL_ET_FK" FOREIGN KEY ("EVENT_TYPE")
	  REFERENCES "SPACEUSER"."RHNVIRTUALINSTANCEEVENTTYPE" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNVIRTUALINSTANCEEVENTLOG" ADD CONSTRAINT "RHN_VIEL_OLD_STATE_FK" FOREIGN KEY ("OLD_STATE")
	  REFERENCES "SPACEUSER"."RHNVIRTUALINSTANCESTATE" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNVIRTUALINSTANCEEVENTLOG" ADD CONSTRAINT "RHN_VIEL_NEW_STATE_FK" FOREIGN KEY ("NEW_STATE")
	  REFERENCES "SPACEUSER"."RHNVIRTUALINSTANCESTATE" ("ID") ENABLE;
