-- created by Oraschemadoc Wed Jan  9 15:07:09 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNVIRTUALINSTANCEINSTALLLOG"
   (	"ID" NUMBER NOT NULL ENABLE,
	"LOG_MESSAGE" VARCHAR2(4000) NOT NULL ENABLE,
	"KS_SESSION_ID" NUMBER,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNVIRTUALINSTANCEINSTALLLOG" ADD CONSTRAINT "RHN_VIIL_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNVIRTUALINSTANCEINSTALLLOG" ADD CONSTRAINT "RHN_VIIL_KS_SID_FK" FOREIGN KEY ("KS_SESSION_ID")
	  REFERENCES "SPACEUSER"."RHNKICKSTARTSESSION" ("ID") ON DELETE CASCADE ENABLE;
