-- created by Oraschemadoc Wed Jan  9 15:07:09 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNWEBCONTACTCHANGESTATE"
   (	"ID" NUMBER,
	"LABEL" VARCHAR2(32) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNWEBCONTACTCHANGESTATE" ADD CONSTRAINT "RHN_CONT_CHANGE_STATE_ID_PK" PRIMARY KEY ("ID") ENABLE;
