-- created by Oraschemadoc Wed Jan  9 15:07:09 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNWEBCONTACTCHANGELOG"
   (	"ID" NUMBER,
	"WEB_CONTACT_ID" NUMBER NOT NULL ENABLE,
	"WEB_CONTACT_FROM_ID" NUMBER,
	"CHANGE_STATE_ID" NUMBER NOT NULL ENABLE,
	"DATE_COMPLETED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNWEBCONTACTCHANGELOG" ADD CONSTRAINT "RHN_WCON_CL_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNWEBCONTACTCHANGELOG" ADD CONSTRAINT "RHN_WCON_CL_WCON_ID_FK" FOREIGN KEY ("WEB_CONTACT_ID")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNWEBCONTACTCHANGELOG" ADD CONSTRAINT "RHN_WCON_CL_WCON_FROM_ID_FK" FOREIGN KEY ("WEB_CONTACT_FROM_ID")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "SPACEUSER"."RHNWEBCONTACTCHANGELOG" ADD CONSTRAINT "RHN_WCON_CL_CSID_FK" FOREIGN KEY ("CHANGE_STATE_ID")
	  REFERENCES "SPACEUSER"."RHNWEBCONTACTCHANGESTATE" ("ID") ENABLE;
