-- created by Oraschemadoc Wed Jan  9 15:07:09 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNXCCDFPROFILE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"IDENTIFIER" VARCHAR2(120) NOT NULL ENABLE,
	"TITLE" VARCHAR2(120) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNXCCDFPROFILE" ADD CONSTRAINT "RHN_XCCDF_PROFILE_ID_PK" PRIMARY KEY ("ID") ENABLE;
