-- created by Oraschemadoc Wed Jan  9 15:07:09 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNXCCDFTESTRESULT"
   (	"ID" NUMBER NOT NULL ENABLE,
	"SERVER_ID" NUMBER NOT NULL ENABLE,
	"ACTION_SCAP_ID" NUMBER NOT NULL ENABLE,
	"BENCHMARK_ID" NUMBER NOT NULL ENABLE,
	"PROFILE_ID" NUMBER NOT NULL ENABLE,
	"IDENTIFIER" VARCHAR2(120) NOT NULL ENABLE,
	"START_TIME" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"END_TIME" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE,
	"ERRORS" BLOB
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNXCCDFTESTRESULT" ADD CONSTRAINT "RHN_XCCDF_TRESULT_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNXCCDFTESTRESULT" ADD CONSTRAINT "RHN_XCCDF_TRESULT_SRVR_FK" FOREIGN KEY ("SERVER_ID")
	  REFERENCES "SPACEUSER"."RHNSERVER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNXCCDFTESTRESULT" ADD CONSTRAINT "RHN_XCCDF_TRESULT_ACT_FK" FOREIGN KEY ("ACTION_SCAP_ID")
	  REFERENCES "SPACEUSER"."RHNACTIONSCAP" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."RHNXCCDFTESTRESULT" ADD CONSTRAINT "RHN_XCCDF_TRESULT_BENCH_FK" FOREIGN KEY ("BENCHMARK_ID")
	  REFERENCES "SPACEUSER"."RHNXCCDFBENCHMARK" ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."RHNXCCDFTESTRESULT" ADD CONSTRAINT "RHN_XCCDF_TRESULT_PROFILE_FK" FOREIGN KEY ("PROFILE_ID")
	  REFERENCES "SPACEUSER"."RHNXCCDFPROFILE" ("ID") ENABLE;
