-- created by Oraschemadoc Wed Jan  9 15:07:09 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNXCCDFRULERESULTTYPE"
   (	"ID" NUMBER NOT NULL ENABLE,
	"ABBREVIATION" CHAR(1) NOT NULL ENABLE,
	"LABEL" VARCHAR2(16) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(120) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNXCCDFRULERESULTTYPE" ADD CONSTRAINT "RHN_XCCDF_RRESULT_T_ID_PK" PRIMARY KEY ("ID") ENABLE;
