-- created by Oraschemadoc Wed Jan  9 15:07:09 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNXCCDFIDENTSYSTEM"
   (	"ID" NUMBER NOT NULL ENABLE,
	"SYSTEM" VARCHAR2(80) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNXCCDFIDENTSYSTEM" ADD CONSTRAINT "RHN_XCCDF_IDENTSYTEM_ID_PK" PRIMARY KEY ("ID") ENABLE;
