-- created by Oraschemadoc Wed Jan  9 15:07:09 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."RHNXCCDFBENCHMARK"
   (	"ID" NUMBER NOT NULL ENABLE,
	"IDENTIFIER" VARCHAR2(120) NOT NULL ENABLE,
	"VERSION" VARCHAR2(80) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."RHNXCCDFBENCHMARK" ADD CONSTRAINT "RHN_XCCDF_BENCHMARK_ID_PK" PRIMARY KEY ("ID") ENABLE;
