-- created by Oraschemadoc Wed Jan  9 15:07:09 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."VALID_COUNTRIES"
   (	"CODE" VARCHAR2(2) NOT NULL ENABLE,
	"SHORT_NAME" VARCHAR2(80) NOT NULL ENABLE,
	"NAME" VARCHAR2(240)
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."VALID_COUNTRIES" ADD CONSTRAINT "VALID_COUNTRIES_PK" PRIMARY KEY ("CODE") ENABLE;
