-- created by Oraschemadoc Wed Jan  9 15:07:10 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."WEB_USER_SITE_INFO"
   (	"ID" NUMBER NOT NULL ENABLE,
	"WEB_USER_ID" NUMBER,
	"EMAIL" VARCHAR2(128),
	"EMAIL_UC" VARCHAR2(128),
	"ALT_FIRST_NAMES" VARCHAR2(128),
	"ALT_LAST_NAME" VARCHAR2(128),
	"ADDRESS1" VARCHAR2(128) NOT NULL ENABLE,
	"ADDRESS2" VARCHAR2(128),
	"ADDRESS3" VARCHAR2(128),
	"ADDRESS4" VARCHAR2(128),
	"CITY" VARCHAR2(128) NOT NULL ENABLE,
	"STATE" VARCHAR2(64),
	"ZIP" VARCHAR2(64),
	"COUNTRY" CHAR(2) NOT NULL ENABLE,
	"PHONE" VARCHAR2(32),
	"FAX" VARCHAR2(32),
	"URL" VARCHAR2(128),
	"IS_PO_BOX" CHAR(1) DEFAULT ('0'),
	"TYPE" CHAR(1),
	"ORACLE_SITE_ID" VARCHAR2(32),
	"NOTES" VARCHAR2(2000),
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp),
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp),
	"ALT_FIRST_NAMES_OL" VARCHAR2(128),
	"ALT_LAST_NAME_OL" VARCHAR2(128),
	"ADDRESS1_OL" VARCHAR2(128),
	"ADDRESS2_OL" VARCHAR2(128),
	"ADDRESS3_OL" VARCHAR2(128),
	"CITY_OL" VARCHAR2(128),
	"STATE_OL" VARCHAR2(32),
	"ZIP_OL" VARCHAR2(32)
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."WEB_USER_SITE_INFO" ADD CONSTRAINT "WUSI_IPB_CK" CHECK (is_po_box in ('1','0')) ENABLE;
  ALTER TABLE "SPACEUSER"."WEB_USER_SITE_INFO" ADD CONSTRAINT "WUSI_ID_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."WEB_USER_SITE_INFO" ADD CONSTRAINT "WUSI_WUID_FK" FOREIGN KEY ("WEB_USER_ID")
	  REFERENCES "SPACEUSER"."WEB_CONTACT" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "SPACEUSER"."WEB_USER_SITE_INFO" ADD CONSTRAINT "WUSI_TYPE_FK" FOREIGN KEY ("TYPE")
	  REFERENCES "SPACEUSER"."WEB_USER_SITE_TYPE" ("TYPE") ENABLE;
