-- created by Oraschemadoc Wed Jan  9 15:07:09 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."WEB_CONTACT"
   (	"ID" NUMBER,
	"ORG_ID" NUMBER NOT NULL ENABLE,
	"LOGIN" VARCHAR2(64) NOT NULL ENABLE,
	"LOGIN_UC" VARCHAR2(64) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(110) NOT NULL ENABLE,
	"CREATED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"MODIFIED" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT (current_timestamp) NOT NULL ENABLE,
	"ORACLE_CONTACT_ID" NUMBER,
	"IGNORE_FLAG" CHAR(1) DEFAULT ('N') NOT NULL ENABLE,
	"READ_ONLY" CHAR(1) DEFAULT ('N') NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."WEB_CONTACT" ADD CONSTRAINT "WEB_CONTACT_IGNORE_CK" CHECK (ignore_flag in ('N','Y')) ENABLE;
  ALTER TABLE "SPACEUSER"."WEB_CONTACT" ADD CONSTRAINT "WEB_CONTACT_RO_CK" CHECK (read_only in ('Y', 'N')) ENABLE;
  ALTER TABLE "SPACEUSER"."WEB_CONTACT" ADD CONSTRAINT "WEB_CONTACT_PK" PRIMARY KEY ("ID") ENABLE;
  ALTER TABLE "SPACEUSER"."WEB_CONTACT" ADD CONSTRAINT "WEB_CONTACT_LOGIN_UC_UNQ" UNIQUE ("LOGIN_UC") ENABLE;
  ALTER TABLE "SPACEUSER"."WEB_CONTACT" ADD CONSTRAINT "WEB_CONTACT_OCID_UNQ" UNIQUE ("ORACLE_CONTACT_ID") ENABLE;
  ALTER TABLE "SPACEUSER"."WEB_CONTACT" ADD CONSTRAINT "WEB_CONTACT_ORG_FK" FOREIGN KEY ("ORG_ID")
	  REFERENCES "SPACEUSER"."WEB_CUSTOMER" ("ID") ENABLE;
