-- created by Oraschemadoc Wed Jan  9 15:07:10 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."WEB_USER_SITE_TYPE"
   (	"TYPE" CHAR(1) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(64) NOT NULL ENABLE
   ) ENABLE ROW MOVEMENT ;
  ALTER TABLE "SPACEUSER"."WEB_USER_SITE_TYPE" ADD CONSTRAINT "WUST_TYPE_PK" PRIMARY KEY ("TYPE") ENABLE;
