-- created by Oraschemadoc Wed Jan  9 15:07:10 2019
-- visit http://www.yarpen.cz/oraschemadoc/ for more info

  CREATE TABLE "SPACEUSER"."WEB_CONTACT_LOG"
   (	"ID" NUMBER NOT NULL ENABLE,
	"LOG_ID" NUMBER NOT NULL ENABLE,
	"ACTION" CHAR(1) NOT NULL ENABLE,
	"ORG_ID" NUMBER NOT NULL ENABLE,
	"LOGIN" VARCHAR2(64) NOT NULL ENABLE,
	"LOGIN_UC" VARCHAR2(64) NOT NULL ENABLE,
	"PASSWORD" VARCHAR2(110) NOT NULL ENABLE,
	"ORACLE_CONTACT_ID" NUMBER,
	"IGNORE_FLAG" CHAR(1) NOT NULL ENABLE,
	"READ_ONLY" CHAR(1) NOT NULL ENABLE
   ) ;
  ALTER TABLE "SPACEUSER"."WEB_CONTACT_LOG" ADD FOREIGN KEY ("LOG_ID")
	  REFERENCES "SPACEUSER"."LOG" ("ID") ENABLE;
